name: flutter_reach_five

packages:
  - flutter_reach_five
  - flutter_reach_five_android
  - flutter_reach_five_ios
  - flutter_reach_five_platform_interface

command:
  bootstrap:
    usePubspecOverrides: true
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false

scripts:
  analyze:
    # We are setting the concurrency to 1 because a higher concurrency can crash
    # the analysis server on low performance machines (like GitHub Actions).
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.
         
  generate:pigeon:
    run: melos exec -- "flutter pub run pigeon --input ./pigeons/reach_five.dart"
    select-package:
      file-exists: "pigeons/reach_five.dart"
         
  test:all:
    run: |
      melos run test --no-select
    description: |
      Run all tests available.

  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --no-pub --test-randomize-ordering-seed random"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists:
        - test
      ignore:
        - '*web*'
        - '*example*'

  test_coverage:all:
    run: |
      melos run test_coverage --no-select
    description: |
      Run all tests available.

  test_coverage:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --coverage --no-pub --test-randomize-ordering-seed random && \
           remove_from_coverage -f coverage/lcov.info -r '\.g\.dart' && \ 
           genhtml coverage/lcov.info -o coverage"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists:
        - test
      ignore:
        - '*web*'
        - '*example*'
  
  open_coverage:all:
    run: |
      melos run open_coverage --no-select
    description: Open coverage for all packages.

  open_coverage:
    run: |
      melos exec -c 6 --fail-fast -- \
        "open coverage/index.html"
    description: Open coverage for a specific package.
    select-package:
      dir-exists:
        - test
      ignore:
        - '*web*'
        - '*example*'
         
  # Additional cleanup lifecycle script, executed when `melos clean` is run.
  postclean: >
    melos exec -c 6 -- "flutter clean"
