// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package tech.bam.flutter_reach_five.android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ReachFiveApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class ProviderCreatorTypeInterface(val raw: Int) {
  GOOGLE(0),
  FACEBOOK(1),
  WEBVIEW(2);

  companion object {
    fun ofRaw(raw: Int): ProviderCreatorTypeInterface? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ProfileAddressTypeInterface(val raw: Int) {
  BILLING(0),
  DELIVERY(1);

  companion object {
    fun ofRaw(raw: Int): ProfileAddressTypeInterface? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ErrorCodesInterface (
  val emailAlreadyInUseCode: String,
  val invalidEmailOrPasswordCode: String,
  val invalidVerificationCode: String,
  val updateSamePassword: String,
  val invalidGrant: String,
  val userCancelledOrClosedTheWebFlow: String,
  val socialAccountEmailAlreadyInUse: String,
  val unauthorizedRefreshToken: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ErrorCodesInterface {
      val emailAlreadyInUseCode = pigeonVar_list[0] as String
      val invalidEmailOrPasswordCode = pigeonVar_list[1] as String
      val invalidVerificationCode = pigeonVar_list[2] as String
      val updateSamePassword = pigeonVar_list[3] as String
      val invalidGrant = pigeonVar_list[4] as String
      val userCancelledOrClosedTheWebFlow = pigeonVar_list[5] as String
      val socialAccountEmailAlreadyInUse = pigeonVar_list[6] as String
      val unauthorizedRefreshToken = pigeonVar_list[7] as String
      return ErrorCodesInterface(emailAlreadyInUseCode, invalidEmailOrPasswordCode, invalidVerificationCode, updateSamePassword, invalidGrant, userCancelledOrClosedTheWebFlow, socialAccountEmailAlreadyInUse, unauthorizedRefreshToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      emailAlreadyInUseCode,
      invalidEmailOrPasswordCode,
      invalidVerificationCode,
      updateSamePassword,
      invalidGrant,
      userCancelledOrClosedTheWebFlow,
      socialAccountEmailAlreadyInUse,
      unauthorizedRefreshToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ErrorCodesInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.emailAlreadyInUseCode, other.emailAlreadyInUseCode) && ReachFiveApiPigeonUtils.deepEquals(this.invalidEmailOrPasswordCode, other.invalidEmailOrPasswordCode) && ReachFiveApiPigeonUtils.deepEquals(this.invalidVerificationCode, other.invalidVerificationCode) && ReachFiveApiPigeonUtils.deepEquals(this.updateSamePassword, other.updateSamePassword) && ReachFiveApiPigeonUtils.deepEquals(this.invalidGrant, other.invalidGrant) && ReachFiveApiPigeonUtils.deepEquals(this.userCancelledOrClosedTheWebFlow, other.userCancelledOrClosedTheWebFlow) && ReachFiveApiPigeonUtils.deepEquals(this.socialAccountEmailAlreadyInUse, other.socialAccountEmailAlreadyInUse) && ReachFiveApiPigeonUtils.deepEquals(this.unauthorizedRefreshToken, other.unauthorizedRefreshToken)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.emailAlreadyInUseCode)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.invalidEmailOrPasswordCode)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.invalidVerificationCode)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.updateSamePassword)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.invalidGrant)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.userCancelledOrClosedTheWebFlow)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.socialAccountEmailAlreadyInUse)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.unauthorizedRefreshToken)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SdkConfigInterface (
  val domain: String,
  val clientId: String,
  val androidScheme: String,
  val iosScheme: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SdkConfigInterface {
      val domain = pigeonVar_list[0] as String
      val clientId = pigeonVar_list[1] as String
      val androidScheme = pigeonVar_list[2] as String
      val iosScheme = pigeonVar_list[3] as String
      return SdkConfigInterface(domain, clientId, androidScheme, iosScheme)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      domain,
      clientId,
      androidScheme,
      iosScheme,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SdkConfigInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.domain, other.domain) && ReachFiveApiPigeonUtils.deepEquals(this.clientId, other.clientId) && ReachFiveApiPigeonUtils.deepEquals(this.androidScheme, other.androidScheme) && ReachFiveApiPigeonUtils.deepEquals(this.iosScheme, other.iosScheme)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.domain)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.clientId)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.androidScheme)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.iosScheme)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProviderCreatorInterface (
  val type: ProviderCreatorTypeInterface
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProviderCreatorInterface {
      val type = pigeonVar_list[0] as ProviderCreatorTypeInterface
      return ProviderCreatorInterface(type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProviderCreatorInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.type, other.type)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.type)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReachFiveKeyInterface (
  val sdkConfig: SdkConfigInterface,
  val providerCreators: List<ProviderCreatorInterface>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReachFiveKeyInterface {
      val sdkConfig = pigeonVar_list[0] as SdkConfigInterface
      val providerCreators = pigeonVar_list[1] as List<ProviderCreatorInterface>
      return ReachFiveKeyInterface(sdkConfig, providerCreators)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sdkConfig,
      providerCreators,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ReachFiveKeyInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.sdkConfig, other.sdkConfig) && ReachFiveApiPigeonUtils.deepEquals(this.providerCreators, other.providerCreators)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.sdkConfig)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.providerCreators)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReachFiveConfigInterface (
  val reachFiveKey: ReachFiveKeyInterface,
  val providers: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReachFiveConfigInterface {
      val reachFiveKey = pigeonVar_list[0] as ReachFiveKeyInterface
      val providers = pigeonVar_list[1] as List<String>
      return ReachFiveConfigInterface(reachFiveKey, providers)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reachFiveKey,
      providers,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ReachFiveConfigInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.reachFiveKey, other.reachFiveKey) && ReachFiveApiPigeonUtils.deepEquals(this.providers, other.providers)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.reachFiveKey)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.providers)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProfileAddressInterface (
  val title: String? = null,
  val isDefault: Boolean? = null,
  val addressType: ProfileAddressTypeInterface? = null,
  val streetAddress: String? = null,
  val locality: String? = null,
  val region: String? = null,
  val postalCode: String? = null,
  val country: String? = null,
  val raw: String? = null,
  val deliveryNote: String? = null,
  val recipient: String? = null,
  val company: String? = null,
  val phoneNumber: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProfileAddressInterface {
      val title = pigeonVar_list[0] as String?
      val isDefault = pigeonVar_list[1] as Boolean?
      val addressType = pigeonVar_list[2] as ProfileAddressTypeInterface?
      val streetAddress = pigeonVar_list[3] as String?
      val locality = pigeonVar_list[4] as String?
      val region = pigeonVar_list[5] as String?
      val postalCode = pigeonVar_list[6] as String?
      val country = pigeonVar_list[7] as String?
      val raw = pigeonVar_list[8] as String?
      val deliveryNote = pigeonVar_list[9] as String?
      val recipient = pigeonVar_list[10] as String?
      val company = pigeonVar_list[11] as String?
      val phoneNumber = pigeonVar_list[12] as String?
      return ProfileAddressInterface(title, isDefault, addressType, streetAddress, locality, region, postalCode, country, raw, deliveryNote, recipient, company, phoneNumber)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      isDefault,
      addressType,
      streetAddress,
      locality,
      region,
      postalCode,
      country,
      raw,
      deliveryNote,
      recipient,
      company,
      phoneNumber,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProfileAddressInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.title, other.title) && ReachFiveApiPigeonUtils.deepEquals(this.isDefault, other.isDefault) && ReachFiveApiPigeonUtils.deepEquals(this.addressType, other.addressType) && ReachFiveApiPigeonUtils.deepEquals(this.streetAddress, other.streetAddress) && ReachFiveApiPigeonUtils.deepEquals(this.locality, other.locality) && ReachFiveApiPigeonUtils.deepEquals(this.region, other.region) && ReachFiveApiPigeonUtils.deepEquals(this.postalCode, other.postalCode) && ReachFiveApiPigeonUtils.deepEquals(this.country, other.country) && ReachFiveApiPigeonUtils.deepEquals(this.raw, other.raw) && ReachFiveApiPigeonUtils.deepEquals(this.deliveryNote, other.deliveryNote) && ReachFiveApiPigeonUtils.deepEquals(this.recipient, other.recipient) && ReachFiveApiPigeonUtils.deepEquals(this.company, other.company) && ReachFiveApiPigeonUtils.deepEquals(this.phoneNumber, other.phoneNumber)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.title)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.isDefault)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.addressType)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.streetAddress)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.locality)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.region)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.postalCode)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.country)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.raw)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.deliveryNote)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.recipient)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.company)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.phoneNumber)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConsentInterface (
  val granted: Boolean,
  val consentType: String? = null,
  val date: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConsentInterface {
      val granted = pigeonVar_list[0] as Boolean
      val consentType = pigeonVar_list[1] as String?
      val date = pigeonVar_list[2] as String
      return ConsentInterface(granted, consentType, date)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      granted,
      consentType,
      date,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConsentInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.granted, other.granted) && ReachFiveApiPigeonUtils.deepEquals(this.consentType, other.consentType) && ReachFiveApiPigeonUtils.deepEquals(this.date, other.date)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.granted)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.consentType)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.date)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProfileSignupRequestInterface (
  val password: String,
  val email: String? = null,
  val phoneNumber: String? = null,
  val givenName: String? = null,
  val middleName: String? = null,
  val familyName: String? = null,
  val name: String? = null,
  val nickname: String? = null,
  val birthdate: String? = null,
  val profileURL: String? = null,
  val picture: String? = null,
  val username: String? = null,
  val gender: String? = null,
  val company: String? = null,
  val addresses: List<ProfileAddressInterface>? = null,
  val locale: String? = null,
  val bio: String? = null,
  val customFields: Map<String, Any?>? = null,
  val consents: Map<String, ConsentInterface>? = null,
  val liteOnly: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProfileSignupRequestInterface {
      val password = pigeonVar_list[0] as String
      val email = pigeonVar_list[1] as String?
      val phoneNumber = pigeonVar_list[2] as String?
      val givenName = pigeonVar_list[3] as String?
      val middleName = pigeonVar_list[4] as String?
      val familyName = pigeonVar_list[5] as String?
      val name = pigeonVar_list[6] as String?
      val nickname = pigeonVar_list[7] as String?
      val birthdate = pigeonVar_list[8] as String?
      val profileURL = pigeonVar_list[9] as String?
      val picture = pigeonVar_list[10] as String?
      val username = pigeonVar_list[11] as String?
      val gender = pigeonVar_list[12] as String?
      val company = pigeonVar_list[13] as String?
      val addresses = pigeonVar_list[14] as List<ProfileAddressInterface>?
      val locale = pigeonVar_list[15] as String?
      val bio = pigeonVar_list[16] as String?
      val customFields = pigeonVar_list[17] as Map<String, Any?>?
      val consents = pigeonVar_list[18] as Map<String, ConsentInterface>?
      val liteOnly = pigeonVar_list[19] as Boolean?
      return ProfileSignupRequestInterface(password, email, phoneNumber, givenName, middleName, familyName, name, nickname, birthdate, profileURL, picture, username, gender, company, addresses, locale, bio, customFields, consents, liteOnly)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      password,
      email,
      phoneNumber,
      givenName,
      middleName,
      familyName,
      name,
      nickname,
      birthdate,
      profileURL,
      picture,
      username,
      gender,
      company,
      addresses,
      locale,
      bio,
      customFields,
      consents,
      liteOnly,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProfileSignupRequestInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.password, other.password) && ReachFiveApiPigeonUtils.deepEquals(this.email, other.email) && ReachFiveApiPigeonUtils.deepEquals(this.phoneNumber, other.phoneNumber) && ReachFiveApiPigeonUtils.deepEquals(this.givenName, other.givenName) && ReachFiveApiPigeonUtils.deepEquals(this.middleName, other.middleName) && ReachFiveApiPigeonUtils.deepEquals(this.familyName, other.familyName) && ReachFiveApiPigeonUtils.deepEquals(this.name, other.name) && ReachFiveApiPigeonUtils.deepEquals(this.nickname, other.nickname) && ReachFiveApiPigeonUtils.deepEquals(this.birthdate, other.birthdate) && ReachFiveApiPigeonUtils.deepEquals(this.profileURL, other.profileURL) && ReachFiveApiPigeonUtils.deepEquals(this.picture, other.picture) && ReachFiveApiPigeonUtils.deepEquals(this.username, other.username) && ReachFiveApiPigeonUtils.deepEquals(this.gender, other.gender) && ReachFiveApiPigeonUtils.deepEquals(this.company, other.company) && ReachFiveApiPigeonUtils.deepEquals(this.addresses, other.addresses) && ReachFiveApiPigeonUtils.deepEquals(this.locale, other.locale) && ReachFiveApiPigeonUtils.deepEquals(this.bio, other.bio) && ReachFiveApiPigeonUtils.deepEquals(this.customFields, other.customFields) && ReachFiveApiPigeonUtils.deepEquals(this.consents, other.consents) && ReachFiveApiPigeonUtils.deepEquals(this.liteOnly, other.liteOnly)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.password)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.email)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.phoneNumber)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.givenName)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.middleName)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.familyName)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.name)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.nickname)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.birthdate)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.profileURL)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.picture)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.username)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.gender)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.company)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.addresses)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.locale)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.bio)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.customFields)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.consents)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.liteOnly)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SignupRequestInterface (
  val reachFiveKey: ReachFiveKeyInterface,
  val profile: ProfileSignupRequestInterface,
  val redirectUrl: String? = null,
  val scope: List<String>? = null,
  val errorCodes: ErrorCodesInterface
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SignupRequestInterface {
      val reachFiveKey = pigeonVar_list[0] as ReachFiveKeyInterface
      val profile = pigeonVar_list[1] as ProfileSignupRequestInterface
      val redirectUrl = pigeonVar_list[2] as String?
      val scope = pigeonVar_list[3] as List<String>?
      val errorCodes = pigeonVar_list[4] as ErrorCodesInterface
      return SignupRequestInterface(reachFiveKey, profile, redirectUrl, scope, errorCodes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reachFiveKey,
      profile,
      redirectUrl,
      scope,
      errorCodes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SignupRequestInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.reachFiveKey, other.reachFiveKey) && ReachFiveApiPigeonUtils.deepEquals(this.profile, other.profile) && ReachFiveApiPigeonUtils.deepEquals(this.redirectUrl, other.redirectUrl) && ReachFiveApiPigeonUtils.deepEquals(this.scope, other.scope) && ReachFiveApiPigeonUtils.deepEquals(this.errorCodes, other.errorCodes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.reachFiveKey)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.profile)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.redirectUrl)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.scope)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.errorCodes)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AddressInterface (
  val formatted: String? = null,
  val streetAddress: String? = null,
  val locality: String? = null,
  val region: String? = null,
  val postalCode: String? = null,
  val country: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AddressInterface {
      val formatted = pigeonVar_list[0] as String?
      val streetAddress = pigeonVar_list[1] as String?
      val locality = pigeonVar_list[2] as String?
      val region = pigeonVar_list[3] as String?
      val postalCode = pigeonVar_list[4] as String?
      val country = pigeonVar_list[5] as String?
      return AddressInterface(formatted, streetAddress, locality, region, postalCode, country)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      formatted,
      streetAddress,
      locality,
      region,
      postalCode,
      country,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AddressInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.formatted, other.formatted) && ReachFiveApiPigeonUtils.deepEquals(this.streetAddress, other.streetAddress) && ReachFiveApiPigeonUtils.deepEquals(this.locality, other.locality) && ReachFiveApiPigeonUtils.deepEquals(this.region, other.region) && ReachFiveApiPigeonUtils.deepEquals(this.postalCode, other.postalCode) && ReachFiveApiPigeonUtils.deepEquals(this.country, other.country)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.formatted)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.streetAddress)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.locality)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.region)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.postalCode)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.country)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OpenIdUserInterface (
  val id: String? = null,
  val name: String? = null,
  val preferredUsername: String? = null,
  val givenName: String? = null,
  val familyName: String? = null,
  val middleName: String? = null,
  val nickname: String? = null,
  val picture: String? = null,
  val website: String? = null,
  val email: String? = null,
  val emailVerified: Boolean? = null,
  val gender: String? = null,
  val zoneinfo: String? = null,
  val locale: String? = null,
  val phoneNumber: String? = null,
  val phoneNumberVerified: Boolean? = null,
  val address: AddressInterface? = null,
  val birthdate: String? = null,
  val externalId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OpenIdUserInterface {
      val id = pigeonVar_list[0] as String?
      val name = pigeonVar_list[1] as String?
      val preferredUsername = pigeonVar_list[2] as String?
      val givenName = pigeonVar_list[3] as String?
      val familyName = pigeonVar_list[4] as String?
      val middleName = pigeonVar_list[5] as String?
      val nickname = pigeonVar_list[6] as String?
      val picture = pigeonVar_list[7] as String?
      val website = pigeonVar_list[8] as String?
      val email = pigeonVar_list[9] as String?
      val emailVerified = pigeonVar_list[10] as Boolean?
      val gender = pigeonVar_list[11] as String?
      val zoneinfo = pigeonVar_list[12] as String?
      val locale = pigeonVar_list[13] as String?
      val phoneNumber = pigeonVar_list[14] as String?
      val phoneNumberVerified = pigeonVar_list[15] as Boolean?
      val address = pigeonVar_list[16] as AddressInterface?
      val birthdate = pigeonVar_list[17] as String?
      val externalId = pigeonVar_list[18] as String?
      return OpenIdUserInterface(id, name, preferredUsername, givenName, familyName, middleName, nickname, picture, website, email, emailVerified, gender, zoneinfo, locale, phoneNumber, phoneNumberVerified, address, birthdate, externalId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      preferredUsername,
      givenName,
      familyName,
      middleName,
      nickname,
      picture,
      website,
      email,
      emailVerified,
      gender,
      zoneinfo,
      locale,
      phoneNumber,
      phoneNumberVerified,
      address,
      birthdate,
      externalId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as OpenIdUserInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.id, other.id) && ReachFiveApiPigeonUtils.deepEquals(this.name, other.name) && ReachFiveApiPigeonUtils.deepEquals(this.preferredUsername, other.preferredUsername) && ReachFiveApiPigeonUtils.deepEquals(this.givenName, other.givenName) && ReachFiveApiPigeonUtils.deepEquals(this.familyName, other.familyName) && ReachFiveApiPigeonUtils.deepEquals(this.middleName, other.middleName) && ReachFiveApiPigeonUtils.deepEquals(this.nickname, other.nickname) && ReachFiveApiPigeonUtils.deepEquals(this.picture, other.picture) && ReachFiveApiPigeonUtils.deepEquals(this.website, other.website) && ReachFiveApiPigeonUtils.deepEquals(this.email, other.email) && ReachFiveApiPigeonUtils.deepEquals(this.emailVerified, other.emailVerified) && ReachFiveApiPigeonUtils.deepEquals(this.gender, other.gender) && ReachFiveApiPigeonUtils.deepEquals(this.zoneinfo, other.zoneinfo) && ReachFiveApiPigeonUtils.deepEquals(this.locale, other.locale) && ReachFiveApiPigeonUtils.deepEquals(this.phoneNumber, other.phoneNumber) && ReachFiveApiPigeonUtils.deepEquals(this.phoneNumberVerified, other.phoneNumberVerified) && ReachFiveApiPigeonUtils.deepEquals(this.address, other.address) && ReachFiveApiPigeonUtils.deepEquals(this.birthdate, other.birthdate) && ReachFiveApiPigeonUtils.deepEquals(this.externalId, other.externalId)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.id)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.name)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.preferredUsername)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.givenName)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.familyName)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.middleName)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.nickname)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.picture)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.website)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.email)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.emailVerified)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.gender)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.zoneinfo)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.locale)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.phoneNumber)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.phoneNumberVerified)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.address)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.birthdate)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.externalId)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AuthTokenInterface (
  val idToken: String? = null,
  val accessToken: String,
  val refreshToken: String? = null,
  val tokenType: String? = null,
  val expiresIn: Long? = null,
  val user: OpenIdUserInterface? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AuthTokenInterface {
      val idToken = pigeonVar_list[0] as String?
      val accessToken = pigeonVar_list[1] as String
      val refreshToken = pigeonVar_list[2] as String?
      val tokenType = pigeonVar_list[3] as String?
      val expiresIn = pigeonVar_list[4] as Long?
      val user = pigeonVar_list[5] as OpenIdUserInterface?
      return AuthTokenInterface(idToken, accessToken, refreshToken, tokenType, expiresIn, user)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      idToken,
      accessToken,
      refreshToken,
      tokenType,
      expiresIn,
      user,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AuthTokenInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.idToken, other.idToken) && ReachFiveApiPigeonUtils.deepEquals(this.accessToken, other.accessToken) && ReachFiveApiPigeonUtils.deepEquals(this.refreshToken, other.refreshToken) && ReachFiveApiPigeonUtils.deepEquals(this.tokenType, other.tokenType) && ReachFiveApiPigeonUtils.deepEquals(this.expiresIn, other.expiresIn) && ReachFiveApiPigeonUtils.deepEquals(this.user, other.user)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.idToken)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.accessToken)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.refreshToken)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.tokenType)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.expiresIn)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.user)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LoginWithPasswordRequestInterface (
  val reachFiveKey: ReachFiveKeyInterface,
  val email: String? = null,
  val phoneNumber: String? = null,
  val password: String,
  val scope: List<String>? = null,
  val errorCodes: ErrorCodesInterface
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LoginWithPasswordRequestInterface {
      val reachFiveKey = pigeonVar_list[0] as ReachFiveKeyInterface
      val email = pigeonVar_list[1] as String?
      val phoneNumber = pigeonVar_list[2] as String?
      val password = pigeonVar_list[3] as String
      val scope = pigeonVar_list[4] as List<String>?
      val errorCodes = pigeonVar_list[5] as ErrorCodesInterface
      return LoginWithPasswordRequestInterface(reachFiveKey, email, phoneNumber, password, scope, errorCodes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reachFiveKey,
      email,
      phoneNumber,
      password,
      scope,
      errorCodes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LoginWithPasswordRequestInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.reachFiveKey, other.reachFiveKey) && ReachFiveApiPigeonUtils.deepEquals(this.email, other.email) && ReachFiveApiPigeonUtils.deepEquals(this.phoneNumber, other.phoneNumber) && ReachFiveApiPigeonUtils.deepEquals(this.password, other.password) && ReachFiveApiPigeonUtils.deepEquals(this.scope, other.scope) && ReachFiveApiPigeonUtils.deepEquals(this.errorCodes, other.errorCodes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.reachFiveKey)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.email)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.phoneNumber)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.password)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.scope)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.errorCodes)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LoginWithProviderRequestInterface (
  val reachFiveKey: ReachFiveKeyInterface,
  val provider: String,
  val origin: String,
  val scope: List<String>? = null,
  val errorCodes: ErrorCodesInterface
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LoginWithProviderRequestInterface {
      val reachFiveKey = pigeonVar_list[0] as ReachFiveKeyInterface
      val provider = pigeonVar_list[1] as String
      val origin = pigeonVar_list[2] as String
      val scope = pigeonVar_list[3] as List<String>?
      val errorCodes = pigeonVar_list[4] as ErrorCodesInterface
      return LoginWithProviderRequestInterface(reachFiveKey, provider, origin, scope, errorCodes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reachFiveKey,
      provider,
      origin,
      scope,
      errorCodes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LoginWithProviderRequestInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.reachFiveKey, other.reachFiveKey) && ReachFiveApiPigeonUtils.deepEquals(this.provider, other.provider) && ReachFiveApiPigeonUtils.deepEquals(this.origin, other.origin) && ReachFiveApiPigeonUtils.deepEquals(this.scope, other.scope) && ReachFiveApiPigeonUtils.deepEquals(this.errorCodes, other.errorCodes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.reachFiveKey)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.provider)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.origin)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.scope)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.errorCodes)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RefreshAccessTokenRequestInterface (
  val reachFiveKey: ReachFiveKeyInterface,
  val authToken: AuthTokenInterface,
  val errorCodes: ErrorCodesInterface
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RefreshAccessTokenRequestInterface {
      val reachFiveKey = pigeonVar_list[0] as ReachFiveKeyInterface
      val authToken = pigeonVar_list[1] as AuthTokenInterface
      val errorCodes = pigeonVar_list[2] as ErrorCodesInterface
      return RefreshAccessTokenRequestInterface(reachFiveKey, authToken, errorCodes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reachFiveKey,
      authToken,
      errorCodes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RefreshAccessTokenRequestInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.reachFiveKey, other.reachFiveKey) && ReachFiveApiPigeonUtils.deepEquals(this.authToken, other.authToken) && ReachFiveApiPigeonUtils.deepEquals(this.errorCodes, other.errorCodes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.reachFiveKey)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.authToken)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.errorCodes)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LoginSummaryInterface (
  val firstLogin: Double? = null,
  val lastLogin: Double? = null,
  val total: Long? = null,
  val origins: List<String>? = null,
  val devices: List<String>? = null,
  val lastProvider: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LoginSummaryInterface {
      val firstLogin = pigeonVar_list[0] as Double?
      val lastLogin = pigeonVar_list[1] as Double?
      val total = pigeonVar_list[2] as Long?
      val origins = pigeonVar_list[3] as List<String>?
      val devices = pigeonVar_list[4] as List<String>?
      val lastProvider = pigeonVar_list[5] as String?
      return LoginSummaryInterface(firstLogin, lastLogin, total, origins, devices, lastProvider)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      firstLogin,
      lastLogin,
      total,
      origins,
      devices,
      lastProvider,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LoginSummaryInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.firstLogin, other.firstLogin) && ReachFiveApiPigeonUtils.deepEquals(this.lastLogin, other.lastLogin) && ReachFiveApiPigeonUtils.deepEquals(this.total, other.total) && ReachFiveApiPigeonUtils.deepEquals(this.origins, other.origins) && ReachFiveApiPigeonUtils.deepEquals(this.devices, other.devices) && ReachFiveApiPigeonUtils.deepEquals(this.lastProvider, other.lastProvider)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.firstLogin)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.lastLogin)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.total)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.origins)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.devices)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.lastProvider)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EmailsInterface (
  val verified: List<String>? = null,
  val unverified: List<String>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EmailsInterface {
      val verified = pigeonVar_list[0] as List<String>?
      val unverified = pigeonVar_list[1] as List<String>?
      return EmailsInterface(verified, unverified)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      verified,
      unverified,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EmailsInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.verified, other.verified) && ReachFiveApiPigeonUtils.deepEquals(this.unverified, other.unverified)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.verified)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.unverified)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ProfileInterface (
  val uid: String? = null,
  val givenName: String? = null,
  val middleName: String? = null,
  val familyName: String? = null,
  val name: String? = null,
  val nickname: String? = null,
  val birthdate: String? = null,
  val profileURL: String? = null,
  val picture: String? = null,
  val externalId: String? = null,
  val authTypes: List<String>? = null,
  val loginSummary: LoginSummaryInterface? = null,
  val username: String? = null,
  val gender: String? = null,
  val email: String? = null,
  val emailVerified: Boolean? = null,
  val emails: EmailsInterface? = null,
  val phoneNumber: String? = null,
  val phoneNumberVerified: Boolean? = null,
  val addresses: List<ProfileAddressInterface>? = null,
  val locale: String? = null,
  val bio: String? = null,
  val customFields: Map<String, Any?>? = null,
  val consents: Map<String, ConsentInterface>? = null,
  val createdAt: String? = null,
  val updatedAt: String? = null,
  val liteOnly: Boolean? = null,
  val company: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProfileInterface {
      val uid = pigeonVar_list[0] as String?
      val givenName = pigeonVar_list[1] as String?
      val middleName = pigeonVar_list[2] as String?
      val familyName = pigeonVar_list[3] as String?
      val name = pigeonVar_list[4] as String?
      val nickname = pigeonVar_list[5] as String?
      val birthdate = pigeonVar_list[6] as String?
      val profileURL = pigeonVar_list[7] as String?
      val picture = pigeonVar_list[8] as String?
      val externalId = pigeonVar_list[9] as String?
      val authTypes = pigeonVar_list[10] as List<String>?
      val loginSummary = pigeonVar_list[11] as LoginSummaryInterface?
      val username = pigeonVar_list[12] as String?
      val gender = pigeonVar_list[13] as String?
      val email = pigeonVar_list[14] as String?
      val emailVerified = pigeonVar_list[15] as Boolean?
      val emails = pigeonVar_list[16] as EmailsInterface?
      val phoneNumber = pigeonVar_list[17] as String?
      val phoneNumberVerified = pigeonVar_list[18] as Boolean?
      val addresses = pigeonVar_list[19] as List<ProfileAddressInterface>?
      val locale = pigeonVar_list[20] as String?
      val bio = pigeonVar_list[21] as String?
      val customFields = pigeonVar_list[22] as Map<String, Any?>?
      val consents = pigeonVar_list[23] as Map<String, ConsentInterface>?
      val createdAt = pigeonVar_list[24] as String?
      val updatedAt = pigeonVar_list[25] as String?
      val liteOnly = pigeonVar_list[26] as Boolean?
      val company = pigeonVar_list[27] as String?
      return ProfileInterface(uid, givenName, middleName, familyName, name, nickname, birthdate, profileURL, picture, externalId, authTypes, loginSummary, username, gender, email, emailVerified, emails, phoneNumber, phoneNumberVerified, addresses, locale, bio, customFields, consents, createdAt, updatedAt, liteOnly, company)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uid,
      givenName,
      middleName,
      familyName,
      name,
      nickname,
      birthdate,
      profileURL,
      picture,
      externalId,
      authTypes,
      loginSummary,
      username,
      gender,
      email,
      emailVerified,
      emails,
      phoneNumber,
      phoneNumberVerified,
      addresses,
      locale,
      bio,
      customFields,
      consents,
      createdAt,
      updatedAt,
      liteOnly,
      company,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ProfileInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.uid, other.uid) && ReachFiveApiPigeonUtils.deepEquals(this.givenName, other.givenName) && ReachFiveApiPigeonUtils.deepEquals(this.middleName, other.middleName) && ReachFiveApiPigeonUtils.deepEquals(this.familyName, other.familyName) && ReachFiveApiPigeonUtils.deepEquals(this.name, other.name) && ReachFiveApiPigeonUtils.deepEquals(this.nickname, other.nickname) && ReachFiveApiPigeonUtils.deepEquals(this.birthdate, other.birthdate) && ReachFiveApiPigeonUtils.deepEquals(this.profileURL, other.profileURL) && ReachFiveApiPigeonUtils.deepEquals(this.picture, other.picture) && ReachFiveApiPigeonUtils.deepEquals(this.externalId, other.externalId) && ReachFiveApiPigeonUtils.deepEquals(this.authTypes, other.authTypes) && ReachFiveApiPigeonUtils.deepEquals(this.loginSummary, other.loginSummary) && ReachFiveApiPigeonUtils.deepEquals(this.username, other.username) && ReachFiveApiPigeonUtils.deepEquals(this.gender, other.gender) && ReachFiveApiPigeonUtils.deepEquals(this.email, other.email) && ReachFiveApiPigeonUtils.deepEquals(this.emailVerified, other.emailVerified) && ReachFiveApiPigeonUtils.deepEquals(this.emails, other.emails) && ReachFiveApiPigeonUtils.deepEquals(this.phoneNumber, other.phoneNumber) && ReachFiveApiPigeonUtils.deepEquals(this.phoneNumberVerified, other.phoneNumberVerified) && ReachFiveApiPigeonUtils.deepEquals(this.addresses, other.addresses) && ReachFiveApiPigeonUtils.deepEquals(this.locale, other.locale) && ReachFiveApiPigeonUtils.deepEquals(this.bio, other.bio) && ReachFiveApiPigeonUtils.deepEquals(this.customFields, other.customFields) && ReachFiveApiPigeonUtils.deepEquals(this.consents, other.consents) && ReachFiveApiPigeonUtils.deepEquals(this.createdAt, other.createdAt) && ReachFiveApiPigeonUtils.deepEquals(this.updatedAt, other.updatedAt) && ReachFiveApiPigeonUtils.deepEquals(this.liteOnly, other.liteOnly) && ReachFiveApiPigeonUtils.deepEquals(this.company, other.company)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.uid)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.givenName)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.middleName)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.familyName)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.name)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.nickname)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.birthdate)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.profileURL)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.picture)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.externalId)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.authTypes)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.loginSummary)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.username)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.gender)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.email)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.emailVerified)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.emails)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.phoneNumber)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.phoneNumberVerified)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.addresses)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.locale)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.bio)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.customFields)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.consents)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.createdAt)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.updatedAt)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.liteOnly)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.company)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GetProfileRequestInterface (
  val reachFiveKey: ReachFiveKeyInterface,
  val authToken: AuthTokenInterface,
  val errorCodes: ErrorCodesInterface
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetProfileRequestInterface {
      val reachFiveKey = pigeonVar_list[0] as ReachFiveKeyInterface
      val authToken = pigeonVar_list[1] as AuthTokenInterface
      val errorCodes = pigeonVar_list[2] as ErrorCodesInterface
      return GetProfileRequestInterface(reachFiveKey, authToken, errorCodes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reachFiveKey,
      authToken,
      errorCodes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetProfileRequestInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.reachFiveKey, other.reachFiveKey) && ReachFiveApiPigeonUtils.deepEquals(this.authToken, other.authToken) && ReachFiveApiPigeonUtils.deepEquals(this.errorCodes, other.errorCodes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.reachFiveKey)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.authToken)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.errorCodes)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UpdateProfileRequestInterface (
  val reachFiveKey: ReachFiveKeyInterface,
  val authToken: AuthTokenInterface,
  val profile: ProfileInterface,
  val errorCodes: ErrorCodesInterface
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UpdateProfileRequestInterface {
      val reachFiveKey = pigeonVar_list[0] as ReachFiveKeyInterface
      val authToken = pigeonVar_list[1] as AuthTokenInterface
      val profile = pigeonVar_list[2] as ProfileInterface
      val errorCodes = pigeonVar_list[3] as ErrorCodesInterface
      return UpdateProfileRequestInterface(reachFiveKey, authToken, profile, errorCodes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reachFiveKey,
      authToken,
      profile,
      errorCodes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UpdateProfileRequestInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.reachFiveKey, other.reachFiveKey) && ReachFiveApiPigeonUtils.deepEquals(this.authToken, other.authToken) && ReachFiveApiPigeonUtils.deepEquals(this.profile, other.profile) && ReachFiveApiPigeonUtils.deepEquals(this.errorCodes, other.errorCodes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.reachFiveKey)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.authToken)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.profile)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.errorCodes)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RequestPasswordResetRequestInterface (
  val reachFiveKey: ReachFiveKeyInterface,
  val email: String? = null,
  val phoneNumber: String? = null,
  val redirectUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RequestPasswordResetRequestInterface {
      val reachFiveKey = pigeonVar_list[0] as ReachFiveKeyInterface
      val email = pigeonVar_list[1] as String?
      val phoneNumber = pigeonVar_list[2] as String?
      val redirectUrl = pigeonVar_list[3] as String?
      return RequestPasswordResetRequestInterface(reachFiveKey, email, phoneNumber, redirectUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reachFiveKey,
      email,
      phoneNumber,
      redirectUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RequestPasswordResetRequestInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.reachFiveKey, other.reachFiveKey) && ReachFiveApiPigeonUtils.deepEquals(this.email, other.email) && ReachFiveApiPigeonUtils.deepEquals(this.phoneNumber, other.phoneNumber) && ReachFiveApiPigeonUtils.deepEquals(this.redirectUrl, other.redirectUrl)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.reachFiveKey)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.email)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.phoneNumber)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.redirectUrl)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UpdatePasswordWithAccessTokenRequestInterface (
  val reachFiveKey: ReachFiveKeyInterface,
  val authToken: AuthTokenInterface,
  val oldPassword: String,
  val password: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UpdatePasswordWithAccessTokenRequestInterface {
      val reachFiveKey = pigeonVar_list[0] as ReachFiveKeyInterface
      val authToken = pigeonVar_list[1] as AuthTokenInterface
      val oldPassword = pigeonVar_list[2] as String
      val password = pigeonVar_list[3] as String
      return UpdatePasswordWithAccessTokenRequestInterface(reachFiveKey, authToken, oldPassword, password)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reachFiveKey,
      authToken,
      oldPassword,
      password,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UpdatePasswordWithAccessTokenRequestInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.reachFiveKey, other.reachFiveKey) && ReachFiveApiPigeonUtils.deepEquals(this.authToken, other.authToken) && ReachFiveApiPigeonUtils.deepEquals(this.oldPassword, other.oldPassword) && ReachFiveApiPigeonUtils.deepEquals(this.password, other.password)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.reachFiveKey)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.authToken)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.oldPassword)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.password)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UpdatePasswordWithFreshAccessTokenRequestInterface (
  val reachFiveKey: ReachFiveKeyInterface,
  val freshAuthToken: AuthTokenInterface,
  val password: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UpdatePasswordWithFreshAccessTokenRequestInterface {
      val reachFiveKey = pigeonVar_list[0] as ReachFiveKeyInterface
      val freshAuthToken = pigeonVar_list[1] as AuthTokenInterface
      val password = pigeonVar_list[2] as String
      return UpdatePasswordWithFreshAccessTokenRequestInterface(reachFiveKey, freshAuthToken, password)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reachFiveKey,
      freshAuthToken,
      password,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UpdatePasswordWithFreshAccessTokenRequestInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.reachFiveKey, other.reachFiveKey) && ReachFiveApiPigeonUtils.deepEquals(this.freshAuthToken, other.freshAuthToken) && ReachFiveApiPigeonUtils.deepEquals(this.password, other.password)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.reachFiveKey)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.freshAuthToken)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.password)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UpdatePasswordWithEmailRequestInterface (
  val reachFiveKey: ReachFiveKeyInterface,
  val email: String,
  val verificationCode: String,
  val password: String,
  val errorCodes: ErrorCodesInterface
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UpdatePasswordWithEmailRequestInterface {
      val reachFiveKey = pigeonVar_list[0] as ReachFiveKeyInterface
      val email = pigeonVar_list[1] as String
      val verificationCode = pigeonVar_list[2] as String
      val password = pigeonVar_list[3] as String
      val errorCodes = pigeonVar_list[4] as ErrorCodesInterface
      return UpdatePasswordWithEmailRequestInterface(reachFiveKey, email, verificationCode, password, errorCodes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reachFiveKey,
      email,
      verificationCode,
      password,
      errorCodes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UpdatePasswordWithEmailRequestInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.reachFiveKey, other.reachFiveKey) && ReachFiveApiPigeonUtils.deepEquals(this.email, other.email) && ReachFiveApiPigeonUtils.deepEquals(this.verificationCode, other.verificationCode) && ReachFiveApiPigeonUtils.deepEquals(this.password, other.password) && ReachFiveApiPigeonUtils.deepEquals(this.errorCodes, other.errorCodes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.reachFiveKey)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.email)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.verificationCode)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.password)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.errorCodes)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UpdatePasswordWithPhoneNumberRequestInterface (
  val reachFiveKey: ReachFiveKeyInterface,
  val phoneNumber: String,
  val verificationCode: String,
  val password: String,
  val errorCodes: ErrorCodesInterface
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UpdatePasswordWithPhoneNumberRequestInterface {
      val reachFiveKey = pigeonVar_list[0] as ReachFiveKeyInterface
      val phoneNumber = pigeonVar_list[1] as String
      val verificationCode = pigeonVar_list[2] as String
      val password = pigeonVar_list[3] as String
      val errorCodes = pigeonVar_list[4] as ErrorCodesInterface
      return UpdatePasswordWithPhoneNumberRequestInterface(reachFiveKey, phoneNumber, verificationCode, password, errorCodes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      reachFiveKey,
      phoneNumber,
      verificationCode,
      password,
      errorCodes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UpdatePasswordWithPhoneNumberRequestInterface
    return ReachFiveApiPigeonUtils.deepEquals(this.reachFiveKey, other.reachFiveKey) && ReachFiveApiPigeonUtils.deepEquals(this.phoneNumber, other.phoneNumber) && ReachFiveApiPigeonUtils.deepEquals(this.verificationCode, other.verificationCode) && ReachFiveApiPigeonUtils.deepEquals(this.password, other.password) && ReachFiveApiPigeonUtils.deepEquals(this.errorCodes, other.errorCodes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.reachFiveKey)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.phoneNumber)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.verificationCode)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.password)
    result = 31 * result + ReachFiveApiPigeonUtils.deepHash(this.errorCodes)
    return result
  }
}
private open class ReachFiveApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ProviderCreatorTypeInterface.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ProfileAddressTypeInterface.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ErrorCodesInterface.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SdkConfigInterface.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProviderCreatorInterface.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReachFiveKeyInterface.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReachFiveConfigInterface.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProfileAddressInterface.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConsentInterface.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProfileSignupRequestInterface.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SignupRequestInterface.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AddressInterface.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OpenIdUserInterface.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AuthTokenInterface.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LoginWithPasswordRequestInterface.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LoginWithProviderRequestInterface.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RefreshAccessTokenRequestInterface.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LoginSummaryInterface.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EmailsInterface.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProfileInterface.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetProfileRequestInterface.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UpdateProfileRequestInterface.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RequestPasswordResetRequestInterface.fromList(it)
        }
      }
      152.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UpdatePasswordWithAccessTokenRequestInterface.fromList(it)
        }
      }
      153.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UpdatePasswordWithFreshAccessTokenRequestInterface.fromList(it)
        }
      }
      154.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UpdatePasswordWithEmailRequestInterface.fromList(it)
        }
      }
      155.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UpdatePasswordWithPhoneNumberRequestInterface.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ProviderCreatorTypeInterface -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ProfileAddressTypeInterface -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is ErrorCodesInterface -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is SdkConfigInterface -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ProviderCreatorInterface -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ReachFiveKeyInterface -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is ReachFiveConfigInterface -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is ProfileAddressInterface -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ConsentInterface -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ProfileSignupRequestInterface -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is SignupRequestInterface -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is AddressInterface -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is OpenIdUserInterface -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is AuthTokenInterface -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is LoginWithPasswordRequestInterface -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is LoginWithProviderRequestInterface -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is RefreshAccessTokenRequestInterface -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is LoginSummaryInterface -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is EmailsInterface -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is ProfileInterface -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is GetProfileRequestInterface -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is UpdateProfileRequestInterface -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is RequestPasswordResetRequestInterface -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      is UpdatePasswordWithAccessTokenRequestInterface -> {
        stream.write(152)
        writeValue(stream, value.toList())
      }
      is UpdatePasswordWithFreshAccessTokenRequestInterface -> {
        stream.write(153)
        writeValue(stream, value.toList())
      }
      is UpdatePasswordWithEmailRequestInterface -> {
        stream.write(154)
        writeValue(stream, value.toList())
      }
      is UpdatePasswordWithPhoneNumberRequestInterface -> {
        stream.write(155)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ReachFiveHostApi {
  fun initialize(reachFiveKey: ReachFiveKeyInterface, callback: (Result<ReachFiveConfigInterface>) -> Unit)
  fun signup(request: SignupRequestInterface, callback: (Result<AuthTokenInterface>) -> Unit)
  fun loginWithPassword(request: LoginWithPasswordRequestInterface, callback: (Result<AuthTokenInterface>) -> Unit)
  fun loginWithProvider(request: LoginWithProviderRequestInterface, callback: (Result<AuthTokenInterface>) -> Unit)
  fun logout(reachFiveKey: ReachFiveKeyInterface, callback: (Result<Unit>) -> Unit)
  fun getProfile(request: GetProfileRequestInterface, callback: (Result<ProfileInterface>) -> Unit)
  fun updateProfile(request: UpdateProfileRequestInterface, callback: (Result<ProfileInterface>) -> Unit)
  fun refreshAccessToken(request: RefreshAccessTokenRequestInterface, callback: (Result<AuthTokenInterface>) -> Unit)
  fun requestPasswordReset(request: RequestPasswordResetRequestInterface, callback: (Result<Unit>) -> Unit)
  fun updatePasswordWithAccessToken(request: UpdatePasswordWithAccessTokenRequestInterface, callback: (Result<Unit>) -> Unit)
  fun updatePasswordWithFreshAccessToken(request: UpdatePasswordWithFreshAccessTokenRequestInterface, callback: (Result<Unit>) -> Unit)
  fun updatePasswordWithEmail(request: UpdatePasswordWithEmailRequestInterface, callback: (Result<Unit>) -> Unit)
  fun updatePasswordWithPhoneNumber(request: UpdatePasswordWithPhoneNumberRequestInterface, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by ReachFiveHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ReachFiveApiPigeonCodec()
    }
    /** Sets up an instance of `ReachFiveHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ReachFiveHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reachFiveKeyArg = args[0] as ReachFiveKeyInterface
            api.initialize(reachFiveKeyArg) { result: Result<ReachFiveConfigInterface> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReachFiveApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ReachFiveApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.signup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SignupRequestInterface
            api.signup(requestArg) { result: Result<AuthTokenInterface> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReachFiveApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ReachFiveApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.loginWithPassword$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as LoginWithPasswordRequestInterface
            api.loginWithPassword(requestArg) { result: Result<AuthTokenInterface> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReachFiveApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ReachFiveApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.loginWithProvider$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as LoginWithProviderRequestInterface
            api.loginWithProvider(requestArg) { result: Result<AuthTokenInterface> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReachFiveApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ReachFiveApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.logout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reachFiveKeyArg = args[0] as ReachFiveKeyInterface
            api.logout(reachFiveKeyArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReachFiveApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ReachFiveApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.getProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as GetProfileRequestInterface
            api.getProfile(requestArg) { result: Result<ProfileInterface> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReachFiveApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ReachFiveApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.updateProfile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as UpdateProfileRequestInterface
            api.updateProfile(requestArg) { result: Result<ProfileInterface> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReachFiveApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ReachFiveApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.refreshAccessToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as RefreshAccessTokenRequestInterface
            api.refreshAccessToken(requestArg) { result: Result<AuthTokenInterface> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReachFiveApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ReachFiveApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.requestPasswordReset$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as RequestPasswordResetRequestInterface
            api.requestPasswordReset(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReachFiveApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ReachFiveApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.updatePasswordWithAccessToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as UpdatePasswordWithAccessTokenRequestInterface
            api.updatePasswordWithAccessToken(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReachFiveApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ReachFiveApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.updatePasswordWithFreshAccessToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as UpdatePasswordWithFreshAccessTokenRequestInterface
            api.updatePasswordWithFreshAccessToken(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReachFiveApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ReachFiveApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.updatePasswordWithEmail$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as UpdatePasswordWithEmailRequestInterface
            api.updatePasswordWithEmail(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReachFiveApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ReachFiveApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.updatePasswordWithPhoneNumber$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as UpdatePasswordWithPhoneNumberRequestInterface
            api.updatePasswordWithPhoneNumber(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReachFiveApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ReachFiveApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
