name: flutter_reach_five_example
description: Demonstrates how to use the flutter_reach_five plugin.
version: 0.1.7
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reach_five:
    # When depending on this package from a real application you should use:
    #   flutter_reach_five: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  # We force analyzer 5.4.0 to avoid version conflicts between the pubspec.lock of
  # reachFice main package and this example
  # cf this issue : https://github.com/invertase/dart_custom_lint/issues/111
  analyzer: 5.4.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
