name: flutter_reach_five_android
description: Android implementation of the flutter_reach_five plugin
version: 0.4.0
homepage: https://github.com/bamlab/Flutter-ReachFive

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

flutter:
  plugin:
    implements: flutter_reach_five
    platforms:
      android:
        package: tech.bam.flutter_reach_five.android
        pluginClass: FlutterReachFivePlugin
        dartPluginClass: FlutterReachFiveAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_reach_five_platform_interface: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
