name: flutter_reach_five_platform_interface
description: A common platform interface for the flutter_reach_five plugin.
version: 0.2.0
homepage: https://github.com/bamlab/Flutter-ReachFive

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  pigeon: ^10.0.0
