name: flutter_reach_five_platform_interface
description: A common platform interface for the flutter_reach_five plugin.
version: 0.4.1
homepage: https://github.com/bamlab/Flutter-ReachFive

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  pigeon: ^17.1.1
