// Autogenerated from Pigeon (v4.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Infos;

@interface Infos : NSObject
+ (instancetype)makeWithInfo1:(nullable NSString *)info1
    info2:(nullable NSString *)info2;
@property(nonatomic, copy, nullable) NSString * info1;
@property(nonatomic, copy, nullable) NSString * info2;
@end

/// The codec used by FLutterInfosApi.
NSObject<FlutterMessageCodec> *FLutterInfosApiGetCodec(void);

@interface FLutterInfosApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onSearchWithCompletion:(void(^)(NSError *_Nullable))completion;
@end
/// The codec used by HostInfosApi.
NSObject<FlutterMessageCodec> *HostInfosApiGetCodec(void);

@protocol HostInfosApi
- (nullable Infos *)searchWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void HostInfosApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HostInfosApi> *_Nullable api);

NS_ASSUME_NONNULL_END
