// Autogenerated from Pigeon (v4.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "info.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ?: [NSNull null]),
        @"message": (error.message ?: [NSNull null]),
        @"details": (error.details ?: [NSNull null]),
        };
  }
  return @{
      @"result": (result ?: [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface Infos ()
+ (Infos *)fromMap:(NSDictionary *)dict;
+ (nullable Infos *)nullableFromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation Infos
+ (instancetype)makeWithInfo1:(nullable NSString *)info1
    info2:(nullable NSString *)info2 {
  Infos* pigeonResult = [[Infos alloc] init];
  pigeonResult.info1 = info1;
  pigeonResult.info2 = info2;
  return pigeonResult;
}
+ (Infos *)fromMap:(NSDictionary *)dict {
  Infos *pigeonResult = [[Infos alloc] init];
  pigeonResult.info1 = GetNullableObject(dict, @"info1");
  pigeonResult.info2 = GetNullableObject(dict, @"info2");
  return pigeonResult;
}
+ (nullable Infos *)nullableFromMap:(NSDictionary *)dict { return (dict) ? [Infos fromMap:dict] : nil; }
- (NSDictionary *)toMap {
  return @{
    @"info1" : (self.info1 ?: [NSNull null]),
    @"info2" : (self.info2 ?: [NSNull null]),
  };
}
@end

@interface FLutterInfosApiCodecReader : FlutterStandardReader
@end
@implementation FLutterInfosApiCodecReader
@end

@interface FLutterInfosApiCodecWriter : FlutterStandardWriter
@end
@implementation FLutterInfosApiCodecWriter
@end

@interface FLutterInfosApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLutterInfosApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FLutterInfosApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FLutterInfosApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FLutterInfosApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    FLutterInfosApiCodecReaderWriter *readerWriter = [[FLutterInfosApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


@interface FLutterInfosApi ()
@property (nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation FLutterInfosApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)onSearchWithCompletion:(void(^)(NSError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.FLutterInfosApi.onSearch"
      binaryMessenger:self.binaryMessenger
      codec:FLutterInfosApiGetCodec()];
  [channel sendMessage:nil reply:^(id reply) {
    completion(nil);
  }];
}
@end
@interface HostInfosApiCodecReader : FlutterStandardReader
@end
@implementation HostInfosApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [Infos fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface HostInfosApiCodecWriter : FlutterStandardWriter
@end
@implementation HostInfosApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[Infos class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface HostInfosApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation HostInfosApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[HostInfosApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[HostInfosApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *HostInfosApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    HostInfosApiCodecReaderWriter *readerWriter = [[HostInfosApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void HostInfosApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HostInfosApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.HostInfosApi.search"
        binaryMessenger:binaryMessenger
        codec:HostInfosApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(searchWithError:)], @"HostInfosApi api (%@) doesn't respond to @selector(searchWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        Infos *output = [api searchWithError:&error];
        callback(wrapResult(output, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
