// Autogenerated from Pigeon (v4.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class ReachFiveConfigInterface;

@interface ReachFiveConfigInterface : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithDomain:(NSString *)domain
    clientId:(NSString *)clientId
    scheme:(NSString *)scheme;
@property(nonatomic, copy) NSString * domain;
@property(nonatomic, copy) NSString * clientId;
@property(nonatomic, copy) NSString * scheme;
@end

/// The codec used by ReachFiveHostApi.
NSObject<FlutterMessageCodec> *ReachFiveHostApiGetCodec(void);

@protocol ReachFiveHostApi
/// @return `nil` only when `error != nil`.
- (nullable ReachFiveConfigInterface *)initializeConfig:(ReachFiveConfigInterface *)config error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void ReachFiveHostApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ReachFiveHostApi> *_Nullable api);

NS_ASSUME_NONNULL_END
