// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsreach_five_api(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashreach_five_api(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsreach_five_api(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsreach_five_api(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsreach_five_api(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsreach_five_api(lhsKey, rhsKey) {
          if deepEqualsreach_five_api(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsreach_five_api(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashreach_five_api(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashreach_five_api(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashreach_five_api(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashreach_five_api(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashreach_five_api(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashreach_five_api(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum ProviderCreatorTypeInterface: Int {
  case google = 0
  case facebook = 1
  case webview = 2
}

enum ProfileAddressTypeInterface: Int {
  case billing = 0
  case delivery = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct ErrorCodesInterface: Hashable {
  var emailAlreadyInUseCode: String
  var invalidEmailOrPasswordCode: String
  var invalidVerificationCode: String
  var updateSamePassword: String
  var invalidGrant: String
  var userCancelledOrClosedTheWebFlow: String
  var socialAccountEmailAlreadyInUse: String
  var unauthorizedRefreshToken: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ErrorCodesInterface? {
    let emailAlreadyInUseCode = pigeonVar_list[0] as! String
    let invalidEmailOrPasswordCode = pigeonVar_list[1] as! String
    let invalidVerificationCode = pigeonVar_list[2] as! String
    let updateSamePassword = pigeonVar_list[3] as! String
    let invalidGrant = pigeonVar_list[4] as! String
    let userCancelledOrClosedTheWebFlow = pigeonVar_list[5] as! String
    let socialAccountEmailAlreadyInUse = pigeonVar_list[6] as! String
    let unauthorizedRefreshToken = pigeonVar_list[7] as! String

    return ErrorCodesInterface(
      emailAlreadyInUseCode: emailAlreadyInUseCode,
      invalidEmailOrPasswordCode: invalidEmailOrPasswordCode,
      invalidVerificationCode: invalidVerificationCode,
      updateSamePassword: updateSamePassword,
      invalidGrant: invalidGrant,
      userCancelledOrClosedTheWebFlow: userCancelledOrClosedTheWebFlow,
      socialAccountEmailAlreadyInUse: socialAccountEmailAlreadyInUse,
      unauthorizedRefreshToken: unauthorizedRefreshToken
    )
  }
  func toList() -> [Any?] {
    return [
      emailAlreadyInUseCode,
      invalidEmailOrPasswordCode,
      invalidVerificationCode,
      updateSamePassword,
      invalidGrant,
      userCancelledOrClosedTheWebFlow,
      socialAccountEmailAlreadyInUse,
      unauthorizedRefreshToken,
    ]
  }
  static func == (lhs: ErrorCodesInterface, rhs: ErrorCodesInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.emailAlreadyInUseCode, rhs.emailAlreadyInUseCode) && deepEqualsreach_five_api(lhs.invalidEmailOrPasswordCode, rhs.invalidEmailOrPasswordCode) && deepEqualsreach_five_api(lhs.invalidVerificationCode, rhs.invalidVerificationCode) && deepEqualsreach_five_api(lhs.updateSamePassword, rhs.updateSamePassword) && deepEqualsreach_five_api(lhs.invalidGrant, rhs.invalidGrant) && deepEqualsreach_five_api(lhs.userCancelledOrClosedTheWebFlow, rhs.userCancelledOrClosedTheWebFlow) && deepEqualsreach_five_api(lhs.socialAccountEmailAlreadyInUse, rhs.socialAccountEmailAlreadyInUse) && deepEqualsreach_five_api(lhs.unauthorizedRefreshToken, rhs.unauthorizedRefreshToken)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ErrorCodesInterface")
    deepHashreach_five_api(value: emailAlreadyInUseCode, hasher: &hasher)
    deepHashreach_five_api(value: invalidEmailOrPasswordCode, hasher: &hasher)
    deepHashreach_five_api(value: invalidVerificationCode, hasher: &hasher)
    deepHashreach_five_api(value: updateSamePassword, hasher: &hasher)
    deepHashreach_five_api(value: invalidGrant, hasher: &hasher)
    deepHashreach_five_api(value: userCancelledOrClosedTheWebFlow, hasher: &hasher)
    deepHashreach_five_api(value: socialAccountEmailAlreadyInUse, hasher: &hasher)
    deepHashreach_five_api(value: unauthorizedRefreshToken, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SdkConfigInterface: Hashable {
  var domain: String
  var clientId: String
  var androidScheme: String
  var iosScheme: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SdkConfigInterface? {
    let domain = pigeonVar_list[0] as! String
    let clientId = pigeonVar_list[1] as! String
    let androidScheme = pigeonVar_list[2] as! String
    let iosScheme = pigeonVar_list[3] as! String

    return SdkConfigInterface(
      domain: domain,
      clientId: clientId,
      androidScheme: androidScheme,
      iosScheme: iosScheme
    )
  }
  func toList() -> [Any?] {
    return [
      domain,
      clientId,
      androidScheme,
      iosScheme,
    ]
  }
  static func == (lhs: SdkConfigInterface, rhs: SdkConfigInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.domain, rhs.domain) && deepEqualsreach_five_api(lhs.clientId, rhs.clientId) && deepEqualsreach_five_api(lhs.androidScheme, rhs.androidScheme) && deepEqualsreach_five_api(lhs.iosScheme, rhs.iosScheme)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SdkConfigInterface")
    deepHashreach_five_api(value: domain, hasher: &hasher)
    deepHashreach_five_api(value: clientId, hasher: &hasher)
    deepHashreach_five_api(value: androidScheme, hasher: &hasher)
    deepHashreach_five_api(value: iosScheme, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProviderCreatorInterface: Hashable {
  var type: ProviderCreatorTypeInterface


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProviderCreatorInterface? {
    let type = pigeonVar_list[0] as! ProviderCreatorTypeInterface

    return ProviderCreatorInterface(
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      type
    ]
  }
  static func == (lhs: ProviderCreatorInterface, rhs: ProviderCreatorInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.type, rhs.type)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProviderCreatorInterface")
    deepHashreach_five_api(value: type, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReachFiveKeyInterface: Hashable {
  var sdkConfig: SdkConfigInterface
  var providerCreators: [ProviderCreatorInterface]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReachFiveKeyInterface? {
    let sdkConfig = pigeonVar_list[0] as! SdkConfigInterface
    let providerCreators = pigeonVar_list[1] as! [ProviderCreatorInterface]

    return ReachFiveKeyInterface(
      sdkConfig: sdkConfig,
      providerCreators: providerCreators
    )
  }
  func toList() -> [Any?] {
    return [
      sdkConfig,
      providerCreators,
    ]
  }
  static func == (lhs: ReachFiveKeyInterface, rhs: ReachFiveKeyInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.sdkConfig, rhs.sdkConfig) && deepEqualsreach_five_api(lhs.providerCreators, rhs.providerCreators)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ReachFiveKeyInterface")
    deepHashreach_five_api(value: sdkConfig, hasher: &hasher)
    deepHashreach_five_api(value: providerCreators, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReachFiveConfigInterface: Hashable {
  var reachFiveKey: ReachFiveKeyInterface
  var providers: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReachFiveConfigInterface? {
    let reachFiveKey = pigeonVar_list[0] as! ReachFiveKeyInterface
    let providers = pigeonVar_list[1] as! [String]

    return ReachFiveConfigInterface(
      reachFiveKey: reachFiveKey,
      providers: providers
    )
  }
  func toList() -> [Any?] {
    return [
      reachFiveKey,
      providers,
    ]
  }
  static func == (lhs: ReachFiveConfigInterface, rhs: ReachFiveConfigInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.reachFiveKey, rhs.reachFiveKey) && deepEqualsreach_five_api(lhs.providers, rhs.providers)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ReachFiveConfigInterface")
    deepHashreach_five_api(value: reachFiveKey, hasher: &hasher)
    deepHashreach_five_api(value: providers, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProfileAddressInterface: Hashable {
  var title: String? = nil
  var isDefault: Bool? = nil
  var addressType: ProfileAddressTypeInterface? = nil
  var streetAddress: String? = nil
  var locality: String? = nil
  var region: String? = nil
  var postalCode: String? = nil
  var country: String? = nil
  var raw: String? = nil
  var deliveryNote: String? = nil
  var recipient: String? = nil
  var company: String? = nil
  var phoneNumber: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProfileAddressInterface? {
    let title: String? = nilOrValue(pigeonVar_list[0])
    let isDefault: Bool? = nilOrValue(pigeonVar_list[1])
    let addressType: ProfileAddressTypeInterface? = nilOrValue(pigeonVar_list[2])
    let streetAddress: String? = nilOrValue(pigeonVar_list[3])
    let locality: String? = nilOrValue(pigeonVar_list[4])
    let region: String? = nilOrValue(pigeonVar_list[5])
    let postalCode: String? = nilOrValue(pigeonVar_list[6])
    let country: String? = nilOrValue(pigeonVar_list[7])
    let raw: String? = nilOrValue(pigeonVar_list[8])
    let deliveryNote: String? = nilOrValue(pigeonVar_list[9])
    let recipient: String? = nilOrValue(pigeonVar_list[10])
    let company: String? = nilOrValue(pigeonVar_list[11])
    let phoneNumber: String? = nilOrValue(pigeonVar_list[12])

    return ProfileAddressInterface(
      title: title,
      isDefault: isDefault,
      addressType: addressType,
      streetAddress: streetAddress,
      locality: locality,
      region: region,
      postalCode: postalCode,
      country: country,
      raw: raw,
      deliveryNote: deliveryNote,
      recipient: recipient,
      company: company,
      phoneNumber: phoneNumber
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      isDefault,
      addressType,
      streetAddress,
      locality,
      region,
      postalCode,
      country,
      raw,
      deliveryNote,
      recipient,
      company,
      phoneNumber,
    ]
  }
  static func == (lhs: ProfileAddressInterface, rhs: ProfileAddressInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.title, rhs.title) && deepEqualsreach_five_api(lhs.isDefault, rhs.isDefault) && deepEqualsreach_five_api(lhs.addressType, rhs.addressType) && deepEqualsreach_five_api(lhs.streetAddress, rhs.streetAddress) && deepEqualsreach_five_api(lhs.locality, rhs.locality) && deepEqualsreach_five_api(lhs.region, rhs.region) && deepEqualsreach_five_api(lhs.postalCode, rhs.postalCode) && deepEqualsreach_five_api(lhs.country, rhs.country) && deepEqualsreach_five_api(lhs.raw, rhs.raw) && deepEqualsreach_five_api(lhs.deliveryNote, rhs.deliveryNote) && deepEqualsreach_five_api(lhs.recipient, rhs.recipient) && deepEqualsreach_five_api(lhs.company, rhs.company) && deepEqualsreach_five_api(lhs.phoneNumber, rhs.phoneNumber)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProfileAddressInterface")
    deepHashreach_five_api(value: title, hasher: &hasher)
    deepHashreach_five_api(value: isDefault, hasher: &hasher)
    deepHashreach_five_api(value: addressType, hasher: &hasher)
    deepHashreach_five_api(value: streetAddress, hasher: &hasher)
    deepHashreach_five_api(value: locality, hasher: &hasher)
    deepHashreach_five_api(value: region, hasher: &hasher)
    deepHashreach_five_api(value: postalCode, hasher: &hasher)
    deepHashreach_five_api(value: country, hasher: &hasher)
    deepHashreach_five_api(value: raw, hasher: &hasher)
    deepHashreach_five_api(value: deliveryNote, hasher: &hasher)
    deepHashreach_five_api(value: recipient, hasher: &hasher)
    deepHashreach_five_api(value: company, hasher: &hasher)
    deepHashreach_five_api(value: phoneNumber, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConsentInterface: Hashable {
  var granted: Bool
  var consentType: String? = nil
  var date: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConsentInterface? {
    let granted = pigeonVar_list[0] as! Bool
    let consentType: String? = nilOrValue(pigeonVar_list[1])
    let date = pigeonVar_list[2] as! String

    return ConsentInterface(
      granted: granted,
      consentType: consentType,
      date: date
    )
  }
  func toList() -> [Any?] {
    return [
      granted,
      consentType,
      date,
    ]
  }
  static func == (lhs: ConsentInterface, rhs: ConsentInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.granted, rhs.granted) && deepEqualsreach_five_api(lhs.consentType, rhs.consentType) && deepEqualsreach_five_api(lhs.date, rhs.date)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConsentInterface")
    deepHashreach_five_api(value: granted, hasher: &hasher)
    deepHashreach_five_api(value: consentType, hasher: &hasher)
    deepHashreach_five_api(value: date, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProfileSignupRequestInterface: Hashable {
  var password: String
  var email: String? = nil
  var phoneNumber: String? = nil
  var givenName: String? = nil
  var middleName: String? = nil
  var familyName: String? = nil
  var name: String? = nil
  var nickname: String? = nil
  var birthdate: String? = nil
  var profileURL: String? = nil
  var picture: String? = nil
  var username: String? = nil
  var gender: String? = nil
  var company: String? = nil
  var addresses: [ProfileAddressInterface]? = nil
  var locale: String? = nil
  var bio: String? = nil
  var customFields: [String: Any?]? = nil
  var consents: [String: ConsentInterface]? = nil
  var liteOnly: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProfileSignupRequestInterface? {
    let password = pigeonVar_list[0] as! String
    let email: String? = nilOrValue(pigeonVar_list[1])
    let phoneNumber: String? = nilOrValue(pigeonVar_list[2])
    let givenName: String? = nilOrValue(pigeonVar_list[3])
    let middleName: String? = nilOrValue(pigeonVar_list[4])
    let familyName: String? = nilOrValue(pigeonVar_list[5])
    let name: String? = nilOrValue(pigeonVar_list[6])
    let nickname: String? = nilOrValue(pigeonVar_list[7])
    let birthdate: String? = nilOrValue(pigeonVar_list[8])
    let profileURL: String? = nilOrValue(pigeonVar_list[9])
    let picture: String? = nilOrValue(pigeonVar_list[10])
    let username: String? = nilOrValue(pigeonVar_list[11])
    let gender: String? = nilOrValue(pigeonVar_list[12])
    let company: String? = nilOrValue(pigeonVar_list[13])
    let addresses: [ProfileAddressInterface]? = nilOrValue(pigeonVar_list[14])
    let locale: String? = nilOrValue(pigeonVar_list[15])
    let bio: String? = nilOrValue(pigeonVar_list[16])
    let customFields: [String: Any?]? = nilOrValue(pigeonVar_list[17])
    let consents: [String: ConsentInterface]? = nilOrValue(pigeonVar_list[18])
    let liteOnly: Bool? = nilOrValue(pigeonVar_list[19])

    return ProfileSignupRequestInterface(
      password: password,
      email: email,
      phoneNumber: phoneNumber,
      givenName: givenName,
      middleName: middleName,
      familyName: familyName,
      name: name,
      nickname: nickname,
      birthdate: birthdate,
      profileURL: profileURL,
      picture: picture,
      username: username,
      gender: gender,
      company: company,
      addresses: addresses,
      locale: locale,
      bio: bio,
      customFields: customFields,
      consents: consents,
      liteOnly: liteOnly
    )
  }
  func toList() -> [Any?] {
    return [
      password,
      email,
      phoneNumber,
      givenName,
      middleName,
      familyName,
      name,
      nickname,
      birthdate,
      profileURL,
      picture,
      username,
      gender,
      company,
      addresses,
      locale,
      bio,
      customFields,
      consents,
      liteOnly,
    ]
  }
  static func == (lhs: ProfileSignupRequestInterface, rhs: ProfileSignupRequestInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.password, rhs.password) && deepEqualsreach_five_api(lhs.email, rhs.email) && deepEqualsreach_five_api(lhs.phoneNumber, rhs.phoneNumber) && deepEqualsreach_five_api(lhs.givenName, rhs.givenName) && deepEqualsreach_five_api(lhs.middleName, rhs.middleName) && deepEqualsreach_five_api(lhs.familyName, rhs.familyName) && deepEqualsreach_five_api(lhs.name, rhs.name) && deepEqualsreach_five_api(lhs.nickname, rhs.nickname) && deepEqualsreach_five_api(lhs.birthdate, rhs.birthdate) && deepEqualsreach_five_api(lhs.profileURL, rhs.profileURL) && deepEqualsreach_five_api(lhs.picture, rhs.picture) && deepEqualsreach_five_api(lhs.username, rhs.username) && deepEqualsreach_five_api(lhs.gender, rhs.gender) && deepEqualsreach_five_api(lhs.company, rhs.company) && deepEqualsreach_five_api(lhs.addresses, rhs.addresses) && deepEqualsreach_five_api(lhs.locale, rhs.locale) && deepEqualsreach_five_api(lhs.bio, rhs.bio) && deepEqualsreach_five_api(lhs.customFields, rhs.customFields) && deepEqualsreach_five_api(lhs.consents, rhs.consents) && deepEqualsreach_five_api(lhs.liteOnly, rhs.liteOnly)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProfileSignupRequestInterface")
    deepHashreach_five_api(value: password, hasher: &hasher)
    deepHashreach_five_api(value: email, hasher: &hasher)
    deepHashreach_five_api(value: phoneNumber, hasher: &hasher)
    deepHashreach_five_api(value: givenName, hasher: &hasher)
    deepHashreach_five_api(value: middleName, hasher: &hasher)
    deepHashreach_five_api(value: familyName, hasher: &hasher)
    deepHashreach_five_api(value: name, hasher: &hasher)
    deepHashreach_five_api(value: nickname, hasher: &hasher)
    deepHashreach_five_api(value: birthdate, hasher: &hasher)
    deepHashreach_five_api(value: profileURL, hasher: &hasher)
    deepHashreach_five_api(value: picture, hasher: &hasher)
    deepHashreach_five_api(value: username, hasher: &hasher)
    deepHashreach_five_api(value: gender, hasher: &hasher)
    deepHashreach_five_api(value: company, hasher: &hasher)
    deepHashreach_five_api(value: addresses, hasher: &hasher)
    deepHashreach_five_api(value: locale, hasher: &hasher)
    deepHashreach_five_api(value: bio, hasher: &hasher)
    deepHashreach_five_api(value: customFields, hasher: &hasher)
    deepHashreach_five_api(value: consents, hasher: &hasher)
    deepHashreach_five_api(value: liteOnly, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SignupRequestInterface: Hashable {
  var reachFiveKey: ReachFiveKeyInterface
  var profile: ProfileSignupRequestInterface
  var redirectUrl: String? = nil
  var scope: [String]? = nil
  var errorCodes: ErrorCodesInterface


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SignupRequestInterface? {
    let reachFiveKey = pigeonVar_list[0] as! ReachFiveKeyInterface
    let profile = pigeonVar_list[1] as! ProfileSignupRequestInterface
    let redirectUrl: String? = nilOrValue(pigeonVar_list[2])
    let scope: [String]? = nilOrValue(pigeonVar_list[3])
    let errorCodes = pigeonVar_list[4] as! ErrorCodesInterface

    return SignupRequestInterface(
      reachFiveKey: reachFiveKey,
      profile: profile,
      redirectUrl: redirectUrl,
      scope: scope,
      errorCodes: errorCodes
    )
  }
  func toList() -> [Any?] {
    return [
      reachFiveKey,
      profile,
      redirectUrl,
      scope,
      errorCodes,
    ]
  }
  static func == (lhs: SignupRequestInterface, rhs: SignupRequestInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.reachFiveKey, rhs.reachFiveKey) && deepEqualsreach_five_api(lhs.profile, rhs.profile) && deepEqualsreach_five_api(lhs.redirectUrl, rhs.redirectUrl) && deepEqualsreach_five_api(lhs.scope, rhs.scope) && deepEqualsreach_five_api(lhs.errorCodes, rhs.errorCodes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SignupRequestInterface")
    deepHashreach_five_api(value: reachFiveKey, hasher: &hasher)
    deepHashreach_five_api(value: profile, hasher: &hasher)
    deepHashreach_five_api(value: redirectUrl, hasher: &hasher)
    deepHashreach_five_api(value: scope, hasher: &hasher)
    deepHashreach_five_api(value: errorCodes, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AddressInterface: Hashable {
  var formatted: String? = nil
  var streetAddress: String? = nil
  var locality: String? = nil
  var region: String? = nil
  var postalCode: String? = nil
  var country: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AddressInterface? {
    let formatted: String? = nilOrValue(pigeonVar_list[0])
    let streetAddress: String? = nilOrValue(pigeonVar_list[1])
    let locality: String? = nilOrValue(pigeonVar_list[2])
    let region: String? = nilOrValue(pigeonVar_list[3])
    let postalCode: String? = nilOrValue(pigeonVar_list[4])
    let country: String? = nilOrValue(pigeonVar_list[5])

    return AddressInterface(
      formatted: formatted,
      streetAddress: streetAddress,
      locality: locality,
      region: region,
      postalCode: postalCode,
      country: country
    )
  }
  func toList() -> [Any?] {
    return [
      formatted,
      streetAddress,
      locality,
      region,
      postalCode,
      country,
    ]
  }
  static func == (lhs: AddressInterface, rhs: AddressInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.formatted, rhs.formatted) && deepEqualsreach_five_api(lhs.streetAddress, rhs.streetAddress) && deepEqualsreach_five_api(lhs.locality, rhs.locality) && deepEqualsreach_five_api(lhs.region, rhs.region) && deepEqualsreach_five_api(lhs.postalCode, rhs.postalCode) && deepEqualsreach_five_api(lhs.country, rhs.country)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AddressInterface")
    deepHashreach_five_api(value: formatted, hasher: &hasher)
    deepHashreach_five_api(value: streetAddress, hasher: &hasher)
    deepHashreach_five_api(value: locality, hasher: &hasher)
    deepHashreach_five_api(value: region, hasher: &hasher)
    deepHashreach_five_api(value: postalCode, hasher: &hasher)
    deepHashreach_five_api(value: country, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OpenIdUserInterface: Hashable {
  var id: String? = nil
  var name: String? = nil
  var preferredUsername: String? = nil
  var givenName: String? = nil
  var familyName: String? = nil
  var middleName: String? = nil
  var nickname: String? = nil
  var picture: String? = nil
  var website: String? = nil
  var email: String? = nil
  var emailVerified: Bool? = nil
  var gender: String? = nil
  var zoneinfo: String? = nil
  var locale: String? = nil
  var phoneNumber: String? = nil
  var phoneNumberVerified: Bool? = nil
  var address: AddressInterface? = nil
  var birthdate: String? = nil
  var externalId: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OpenIdUserInterface? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let name: String? = nilOrValue(pigeonVar_list[1])
    let preferredUsername: String? = nilOrValue(pigeonVar_list[2])
    let givenName: String? = nilOrValue(pigeonVar_list[3])
    let familyName: String? = nilOrValue(pigeonVar_list[4])
    let middleName: String? = nilOrValue(pigeonVar_list[5])
    let nickname: String? = nilOrValue(pigeonVar_list[6])
    let picture: String? = nilOrValue(pigeonVar_list[7])
    let website: String? = nilOrValue(pigeonVar_list[8])
    let email: String? = nilOrValue(pigeonVar_list[9])
    let emailVerified: Bool? = nilOrValue(pigeonVar_list[10])
    let gender: String? = nilOrValue(pigeonVar_list[11])
    let zoneinfo: String? = nilOrValue(pigeonVar_list[12])
    let locale: String? = nilOrValue(pigeonVar_list[13])
    let phoneNumber: String? = nilOrValue(pigeonVar_list[14])
    let phoneNumberVerified: Bool? = nilOrValue(pigeonVar_list[15])
    let address: AddressInterface? = nilOrValue(pigeonVar_list[16])
    let birthdate: String? = nilOrValue(pigeonVar_list[17])
    let externalId: String? = nilOrValue(pigeonVar_list[18])

    return OpenIdUserInterface(
      id: id,
      name: name,
      preferredUsername: preferredUsername,
      givenName: givenName,
      familyName: familyName,
      middleName: middleName,
      nickname: nickname,
      picture: picture,
      website: website,
      email: email,
      emailVerified: emailVerified,
      gender: gender,
      zoneinfo: zoneinfo,
      locale: locale,
      phoneNumber: phoneNumber,
      phoneNumberVerified: phoneNumberVerified,
      address: address,
      birthdate: birthdate,
      externalId: externalId
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      name,
      preferredUsername,
      givenName,
      familyName,
      middleName,
      nickname,
      picture,
      website,
      email,
      emailVerified,
      gender,
      zoneinfo,
      locale,
      phoneNumber,
      phoneNumberVerified,
      address,
      birthdate,
      externalId,
    ]
  }
  static func == (lhs: OpenIdUserInterface, rhs: OpenIdUserInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.id, rhs.id) && deepEqualsreach_five_api(lhs.name, rhs.name) && deepEqualsreach_five_api(lhs.preferredUsername, rhs.preferredUsername) && deepEqualsreach_five_api(lhs.givenName, rhs.givenName) && deepEqualsreach_five_api(lhs.familyName, rhs.familyName) && deepEqualsreach_five_api(lhs.middleName, rhs.middleName) && deepEqualsreach_five_api(lhs.nickname, rhs.nickname) && deepEqualsreach_five_api(lhs.picture, rhs.picture) && deepEqualsreach_five_api(lhs.website, rhs.website) && deepEqualsreach_five_api(lhs.email, rhs.email) && deepEqualsreach_five_api(lhs.emailVerified, rhs.emailVerified) && deepEqualsreach_five_api(lhs.gender, rhs.gender) && deepEqualsreach_five_api(lhs.zoneinfo, rhs.zoneinfo) && deepEqualsreach_five_api(lhs.locale, rhs.locale) && deepEqualsreach_five_api(lhs.phoneNumber, rhs.phoneNumber) && deepEqualsreach_five_api(lhs.phoneNumberVerified, rhs.phoneNumberVerified) && deepEqualsreach_five_api(lhs.address, rhs.address) && deepEqualsreach_five_api(lhs.birthdate, rhs.birthdate) && deepEqualsreach_five_api(lhs.externalId, rhs.externalId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OpenIdUserInterface")
    deepHashreach_five_api(value: id, hasher: &hasher)
    deepHashreach_five_api(value: name, hasher: &hasher)
    deepHashreach_five_api(value: preferredUsername, hasher: &hasher)
    deepHashreach_five_api(value: givenName, hasher: &hasher)
    deepHashreach_five_api(value: familyName, hasher: &hasher)
    deepHashreach_five_api(value: middleName, hasher: &hasher)
    deepHashreach_five_api(value: nickname, hasher: &hasher)
    deepHashreach_five_api(value: picture, hasher: &hasher)
    deepHashreach_five_api(value: website, hasher: &hasher)
    deepHashreach_five_api(value: email, hasher: &hasher)
    deepHashreach_five_api(value: emailVerified, hasher: &hasher)
    deepHashreach_five_api(value: gender, hasher: &hasher)
    deepHashreach_five_api(value: zoneinfo, hasher: &hasher)
    deepHashreach_five_api(value: locale, hasher: &hasher)
    deepHashreach_five_api(value: phoneNumber, hasher: &hasher)
    deepHashreach_five_api(value: phoneNumberVerified, hasher: &hasher)
    deepHashreach_five_api(value: address, hasher: &hasher)
    deepHashreach_five_api(value: birthdate, hasher: &hasher)
    deepHashreach_five_api(value: externalId, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AuthTokenInterface: Hashable {
  var idToken: String? = nil
  var accessToken: String
  var refreshToken: String? = nil
  var tokenType: String? = nil
  var expiresIn: Int64? = nil
  var user: OpenIdUserInterface? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AuthTokenInterface? {
    let idToken: String? = nilOrValue(pigeonVar_list[0])
    let accessToken = pigeonVar_list[1] as! String
    let refreshToken: String? = nilOrValue(pigeonVar_list[2])
    let tokenType: String? = nilOrValue(pigeonVar_list[3])
    let expiresIn: Int64? = nilOrValue(pigeonVar_list[4])
    let user: OpenIdUserInterface? = nilOrValue(pigeonVar_list[5])

    return AuthTokenInterface(
      idToken: idToken,
      accessToken: accessToken,
      refreshToken: refreshToken,
      tokenType: tokenType,
      expiresIn: expiresIn,
      user: user
    )
  }
  func toList() -> [Any?] {
    return [
      idToken,
      accessToken,
      refreshToken,
      tokenType,
      expiresIn,
      user,
    ]
  }
  static func == (lhs: AuthTokenInterface, rhs: AuthTokenInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.idToken, rhs.idToken) && deepEqualsreach_five_api(lhs.accessToken, rhs.accessToken) && deepEqualsreach_five_api(lhs.refreshToken, rhs.refreshToken) && deepEqualsreach_five_api(lhs.tokenType, rhs.tokenType) && deepEqualsreach_five_api(lhs.expiresIn, rhs.expiresIn) && deepEqualsreach_five_api(lhs.user, rhs.user)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AuthTokenInterface")
    deepHashreach_five_api(value: idToken, hasher: &hasher)
    deepHashreach_five_api(value: accessToken, hasher: &hasher)
    deepHashreach_five_api(value: refreshToken, hasher: &hasher)
    deepHashreach_five_api(value: tokenType, hasher: &hasher)
    deepHashreach_five_api(value: expiresIn, hasher: &hasher)
    deepHashreach_five_api(value: user, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LoginWithPasswordRequestInterface: Hashable {
  var reachFiveKey: ReachFiveKeyInterface
  var email: String? = nil
  var phoneNumber: String? = nil
  var password: String
  var scope: [String]? = nil
  var errorCodes: ErrorCodesInterface


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LoginWithPasswordRequestInterface? {
    let reachFiveKey = pigeonVar_list[0] as! ReachFiveKeyInterface
    let email: String? = nilOrValue(pigeonVar_list[1])
    let phoneNumber: String? = nilOrValue(pigeonVar_list[2])
    let password = pigeonVar_list[3] as! String
    let scope: [String]? = nilOrValue(pigeonVar_list[4])
    let errorCodes = pigeonVar_list[5] as! ErrorCodesInterface

    return LoginWithPasswordRequestInterface(
      reachFiveKey: reachFiveKey,
      email: email,
      phoneNumber: phoneNumber,
      password: password,
      scope: scope,
      errorCodes: errorCodes
    )
  }
  func toList() -> [Any?] {
    return [
      reachFiveKey,
      email,
      phoneNumber,
      password,
      scope,
      errorCodes,
    ]
  }
  static func == (lhs: LoginWithPasswordRequestInterface, rhs: LoginWithPasswordRequestInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.reachFiveKey, rhs.reachFiveKey) && deepEqualsreach_five_api(lhs.email, rhs.email) && deepEqualsreach_five_api(lhs.phoneNumber, rhs.phoneNumber) && deepEqualsreach_five_api(lhs.password, rhs.password) && deepEqualsreach_five_api(lhs.scope, rhs.scope) && deepEqualsreach_five_api(lhs.errorCodes, rhs.errorCodes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LoginWithPasswordRequestInterface")
    deepHashreach_five_api(value: reachFiveKey, hasher: &hasher)
    deepHashreach_five_api(value: email, hasher: &hasher)
    deepHashreach_five_api(value: phoneNumber, hasher: &hasher)
    deepHashreach_five_api(value: password, hasher: &hasher)
    deepHashreach_five_api(value: scope, hasher: &hasher)
    deepHashreach_five_api(value: errorCodes, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LoginWithProviderRequestInterface: Hashable {
  var reachFiveKey: ReachFiveKeyInterface
  var provider: String
  var origin: String
  var scope: [String]? = nil
  var errorCodes: ErrorCodesInterface


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LoginWithProviderRequestInterface? {
    let reachFiveKey = pigeonVar_list[0] as! ReachFiveKeyInterface
    let provider = pigeonVar_list[1] as! String
    let origin = pigeonVar_list[2] as! String
    let scope: [String]? = nilOrValue(pigeonVar_list[3])
    let errorCodes = pigeonVar_list[4] as! ErrorCodesInterface

    return LoginWithProviderRequestInterface(
      reachFiveKey: reachFiveKey,
      provider: provider,
      origin: origin,
      scope: scope,
      errorCodes: errorCodes
    )
  }
  func toList() -> [Any?] {
    return [
      reachFiveKey,
      provider,
      origin,
      scope,
      errorCodes,
    ]
  }
  static func == (lhs: LoginWithProviderRequestInterface, rhs: LoginWithProviderRequestInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.reachFiveKey, rhs.reachFiveKey) && deepEqualsreach_five_api(lhs.provider, rhs.provider) && deepEqualsreach_five_api(lhs.origin, rhs.origin) && deepEqualsreach_five_api(lhs.scope, rhs.scope) && deepEqualsreach_five_api(lhs.errorCodes, rhs.errorCodes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LoginWithProviderRequestInterface")
    deepHashreach_five_api(value: reachFiveKey, hasher: &hasher)
    deepHashreach_five_api(value: provider, hasher: &hasher)
    deepHashreach_five_api(value: origin, hasher: &hasher)
    deepHashreach_five_api(value: scope, hasher: &hasher)
    deepHashreach_five_api(value: errorCodes, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RefreshAccessTokenRequestInterface: Hashable {
  var reachFiveKey: ReachFiveKeyInterface
  var authToken: AuthTokenInterface
  var errorCodes: ErrorCodesInterface


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RefreshAccessTokenRequestInterface? {
    let reachFiveKey = pigeonVar_list[0] as! ReachFiveKeyInterface
    let authToken = pigeonVar_list[1] as! AuthTokenInterface
    let errorCodes = pigeonVar_list[2] as! ErrorCodesInterface

    return RefreshAccessTokenRequestInterface(
      reachFiveKey: reachFiveKey,
      authToken: authToken,
      errorCodes: errorCodes
    )
  }
  func toList() -> [Any?] {
    return [
      reachFiveKey,
      authToken,
      errorCodes,
    ]
  }
  static func == (lhs: RefreshAccessTokenRequestInterface, rhs: RefreshAccessTokenRequestInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.reachFiveKey, rhs.reachFiveKey) && deepEqualsreach_five_api(lhs.authToken, rhs.authToken) && deepEqualsreach_five_api(lhs.errorCodes, rhs.errorCodes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RefreshAccessTokenRequestInterface")
    deepHashreach_five_api(value: reachFiveKey, hasher: &hasher)
    deepHashreach_five_api(value: authToken, hasher: &hasher)
    deepHashreach_five_api(value: errorCodes, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LoginSummaryInterface: Hashable {
  var firstLogin: Double? = nil
  var lastLogin: Double? = nil
  var total: Int64? = nil
  var origins: [String]? = nil
  var devices: [String]? = nil
  var lastProvider: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LoginSummaryInterface? {
    let firstLogin: Double? = nilOrValue(pigeonVar_list[0])
    let lastLogin: Double? = nilOrValue(pigeonVar_list[1])
    let total: Int64? = nilOrValue(pigeonVar_list[2])
    let origins: [String]? = nilOrValue(pigeonVar_list[3])
    let devices: [String]? = nilOrValue(pigeonVar_list[4])
    let lastProvider: String? = nilOrValue(pigeonVar_list[5])

    return LoginSummaryInterface(
      firstLogin: firstLogin,
      lastLogin: lastLogin,
      total: total,
      origins: origins,
      devices: devices,
      lastProvider: lastProvider
    )
  }
  func toList() -> [Any?] {
    return [
      firstLogin,
      lastLogin,
      total,
      origins,
      devices,
      lastProvider,
    ]
  }
  static func == (lhs: LoginSummaryInterface, rhs: LoginSummaryInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.firstLogin, rhs.firstLogin) && deepEqualsreach_five_api(lhs.lastLogin, rhs.lastLogin) && deepEqualsreach_five_api(lhs.total, rhs.total) && deepEqualsreach_five_api(lhs.origins, rhs.origins) && deepEqualsreach_five_api(lhs.devices, rhs.devices) && deepEqualsreach_five_api(lhs.lastProvider, rhs.lastProvider)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LoginSummaryInterface")
    deepHashreach_five_api(value: firstLogin, hasher: &hasher)
    deepHashreach_five_api(value: lastLogin, hasher: &hasher)
    deepHashreach_five_api(value: total, hasher: &hasher)
    deepHashreach_five_api(value: origins, hasher: &hasher)
    deepHashreach_five_api(value: devices, hasher: &hasher)
    deepHashreach_five_api(value: lastProvider, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct EmailsInterface: Hashable {
  var verified: [String]? = nil
  var unverified: [String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EmailsInterface? {
    let verified: [String]? = nilOrValue(pigeonVar_list[0])
    let unverified: [String]? = nilOrValue(pigeonVar_list[1])

    return EmailsInterface(
      verified: verified,
      unverified: unverified
    )
  }
  func toList() -> [Any?] {
    return [
      verified,
      unverified,
    ]
  }
  static func == (lhs: EmailsInterface, rhs: EmailsInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.verified, rhs.verified) && deepEqualsreach_five_api(lhs.unverified, rhs.unverified)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EmailsInterface")
    deepHashreach_five_api(value: verified, hasher: &hasher)
    deepHashreach_five_api(value: unverified, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProfileInterface: Hashable {
  var uid: String? = nil
  var givenName: String? = nil
  var middleName: String? = nil
  var familyName: String? = nil
  var name: String? = nil
  var nickname: String? = nil
  var birthdate: String? = nil
  var profileURL: String? = nil
  var picture: String? = nil
  var externalId: String? = nil
  var authTypes: [String]? = nil
  var loginSummary: LoginSummaryInterface? = nil
  var username: String? = nil
  var gender: String? = nil
  var email: String? = nil
  var emailVerified: Bool? = nil
  var emails: EmailsInterface? = nil
  var phoneNumber: String? = nil
  var phoneNumberVerified: Bool? = nil
  var addresses: [ProfileAddressInterface]? = nil
  var locale: String? = nil
  var bio: String? = nil
  var customFields: [String: Any?]? = nil
  var consents: [String: ConsentInterface]? = nil
  var createdAt: String? = nil
  var updatedAt: String? = nil
  var liteOnly: Bool? = nil
  var company: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProfileInterface? {
    let uid: String? = nilOrValue(pigeonVar_list[0])
    let givenName: String? = nilOrValue(pigeonVar_list[1])
    let middleName: String? = nilOrValue(pigeonVar_list[2])
    let familyName: String? = nilOrValue(pigeonVar_list[3])
    let name: String? = nilOrValue(pigeonVar_list[4])
    let nickname: String? = nilOrValue(pigeonVar_list[5])
    let birthdate: String? = nilOrValue(pigeonVar_list[6])
    let profileURL: String? = nilOrValue(pigeonVar_list[7])
    let picture: String? = nilOrValue(pigeonVar_list[8])
    let externalId: String? = nilOrValue(pigeonVar_list[9])
    let authTypes: [String]? = nilOrValue(pigeonVar_list[10])
    let loginSummary: LoginSummaryInterface? = nilOrValue(pigeonVar_list[11])
    let username: String? = nilOrValue(pigeonVar_list[12])
    let gender: String? = nilOrValue(pigeonVar_list[13])
    let email: String? = nilOrValue(pigeonVar_list[14])
    let emailVerified: Bool? = nilOrValue(pigeonVar_list[15])
    let emails: EmailsInterface? = nilOrValue(pigeonVar_list[16])
    let phoneNumber: String? = nilOrValue(pigeonVar_list[17])
    let phoneNumberVerified: Bool? = nilOrValue(pigeonVar_list[18])
    let addresses: [ProfileAddressInterface]? = nilOrValue(pigeonVar_list[19])
    let locale: String? = nilOrValue(pigeonVar_list[20])
    let bio: String? = nilOrValue(pigeonVar_list[21])
    let customFields: [String: Any?]? = nilOrValue(pigeonVar_list[22])
    let consents: [String: ConsentInterface]? = nilOrValue(pigeonVar_list[23])
    let createdAt: String? = nilOrValue(pigeonVar_list[24])
    let updatedAt: String? = nilOrValue(pigeonVar_list[25])
    let liteOnly: Bool? = nilOrValue(pigeonVar_list[26])
    let company: String? = nilOrValue(pigeonVar_list[27])

    return ProfileInterface(
      uid: uid,
      givenName: givenName,
      middleName: middleName,
      familyName: familyName,
      name: name,
      nickname: nickname,
      birthdate: birthdate,
      profileURL: profileURL,
      picture: picture,
      externalId: externalId,
      authTypes: authTypes,
      loginSummary: loginSummary,
      username: username,
      gender: gender,
      email: email,
      emailVerified: emailVerified,
      emails: emails,
      phoneNumber: phoneNumber,
      phoneNumberVerified: phoneNumberVerified,
      addresses: addresses,
      locale: locale,
      bio: bio,
      customFields: customFields,
      consents: consents,
      createdAt: createdAt,
      updatedAt: updatedAt,
      liteOnly: liteOnly,
      company: company
    )
  }
  func toList() -> [Any?] {
    return [
      uid,
      givenName,
      middleName,
      familyName,
      name,
      nickname,
      birthdate,
      profileURL,
      picture,
      externalId,
      authTypes,
      loginSummary,
      username,
      gender,
      email,
      emailVerified,
      emails,
      phoneNumber,
      phoneNumberVerified,
      addresses,
      locale,
      bio,
      customFields,
      consents,
      createdAt,
      updatedAt,
      liteOnly,
      company,
    ]
  }
  static func == (lhs: ProfileInterface, rhs: ProfileInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.uid, rhs.uid) && deepEqualsreach_five_api(lhs.givenName, rhs.givenName) && deepEqualsreach_five_api(lhs.middleName, rhs.middleName) && deepEqualsreach_five_api(lhs.familyName, rhs.familyName) && deepEqualsreach_five_api(lhs.name, rhs.name) && deepEqualsreach_five_api(lhs.nickname, rhs.nickname) && deepEqualsreach_five_api(lhs.birthdate, rhs.birthdate) && deepEqualsreach_five_api(lhs.profileURL, rhs.profileURL) && deepEqualsreach_five_api(lhs.picture, rhs.picture) && deepEqualsreach_five_api(lhs.externalId, rhs.externalId) && deepEqualsreach_five_api(lhs.authTypes, rhs.authTypes) && deepEqualsreach_five_api(lhs.loginSummary, rhs.loginSummary) && deepEqualsreach_five_api(lhs.username, rhs.username) && deepEqualsreach_five_api(lhs.gender, rhs.gender) && deepEqualsreach_five_api(lhs.email, rhs.email) && deepEqualsreach_five_api(lhs.emailVerified, rhs.emailVerified) && deepEqualsreach_five_api(lhs.emails, rhs.emails) && deepEqualsreach_five_api(lhs.phoneNumber, rhs.phoneNumber) && deepEqualsreach_five_api(lhs.phoneNumberVerified, rhs.phoneNumberVerified) && deepEqualsreach_five_api(lhs.addresses, rhs.addresses) && deepEqualsreach_five_api(lhs.locale, rhs.locale) && deepEqualsreach_five_api(lhs.bio, rhs.bio) && deepEqualsreach_five_api(lhs.customFields, rhs.customFields) && deepEqualsreach_five_api(lhs.consents, rhs.consents) && deepEqualsreach_five_api(lhs.createdAt, rhs.createdAt) && deepEqualsreach_five_api(lhs.updatedAt, rhs.updatedAt) && deepEqualsreach_five_api(lhs.liteOnly, rhs.liteOnly) && deepEqualsreach_five_api(lhs.company, rhs.company)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProfileInterface")
    deepHashreach_five_api(value: uid, hasher: &hasher)
    deepHashreach_five_api(value: givenName, hasher: &hasher)
    deepHashreach_five_api(value: middleName, hasher: &hasher)
    deepHashreach_five_api(value: familyName, hasher: &hasher)
    deepHashreach_five_api(value: name, hasher: &hasher)
    deepHashreach_five_api(value: nickname, hasher: &hasher)
    deepHashreach_five_api(value: birthdate, hasher: &hasher)
    deepHashreach_five_api(value: profileURL, hasher: &hasher)
    deepHashreach_five_api(value: picture, hasher: &hasher)
    deepHashreach_five_api(value: externalId, hasher: &hasher)
    deepHashreach_five_api(value: authTypes, hasher: &hasher)
    deepHashreach_five_api(value: loginSummary, hasher: &hasher)
    deepHashreach_five_api(value: username, hasher: &hasher)
    deepHashreach_five_api(value: gender, hasher: &hasher)
    deepHashreach_five_api(value: email, hasher: &hasher)
    deepHashreach_five_api(value: emailVerified, hasher: &hasher)
    deepHashreach_five_api(value: emails, hasher: &hasher)
    deepHashreach_five_api(value: phoneNumber, hasher: &hasher)
    deepHashreach_five_api(value: phoneNumberVerified, hasher: &hasher)
    deepHashreach_five_api(value: addresses, hasher: &hasher)
    deepHashreach_five_api(value: locale, hasher: &hasher)
    deepHashreach_five_api(value: bio, hasher: &hasher)
    deepHashreach_five_api(value: customFields, hasher: &hasher)
    deepHashreach_five_api(value: consents, hasher: &hasher)
    deepHashreach_five_api(value: createdAt, hasher: &hasher)
    deepHashreach_five_api(value: updatedAt, hasher: &hasher)
    deepHashreach_five_api(value: liteOnly, hasher: &hasher)
    deepHashreach_five_api(value: company, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GetProfileRequestInterface: Hashable {
  var reachFiveKey: ReachFiveKeyInterface
  var authToken: AuthTokenInterface
  var errorCodes: ErrorCodesInterface


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GetProfileRequestInterface? {
    let reachFiveKey = pigeonVar_list[0] as! ReachFiveKeyInterface
    let authToken = pigeonVar_list[1] as! AuthTokenInterface
    let errorCodes = pigeonVar_list[2] as! ErrorCodesInterface

    return GetProfileRequestInterface(
      reachFiveKey: reachFiveKey,
      authToken: authToken,
      errorCodes: errorCodes
    )
  }
  func toList() -> [Any?] {
    return [
      reachFiveKey,
      authToken,
      errorCodes,
    ]
  }
  static func == (lhs: GetProfileRequestInterface, rhs: GetProfileRequestInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.reachFiveKey, rhs.reachFiveKey) && deepEqualsreach_five_api(lhs.authToken, rhs.authToken) && deepEqualsreach_five_api(lhs.errorCodes, rhs.errorCodes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GetProfileRequestInterface")
    deepHashreach_five_api(value: reachFiveKey, hasher: &hasher)
    deepHashreach_five_api(value: authToken, hasher: &hasher)
    deepHashreach_five_api(value: errorCodes, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UpdateProfileRequestInterface: Hashable {
  var reachFiveKey: ReachFiveKeyInterface
  var authToken: AuthTokenInterface
  var profile: ProfileInterface
  var errorCodes: ErrorCodesInterface


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UpdateProfileRequestInterface? {
    let reachFiveKey = pigeonVar_list[0] as! ReachFiveKeyInterface
    let authToken = pigeonVar_list[1] as! AuthTokenInterface
    let profile = pigeonVar_list[2] as! ProfileInterface
    let errorCodes = pigeonVar_list[3] as! ErrorCodesInterface

    return UpdateProfileRequestInterface(
      reachFiveKey: reachFiveKey,
      authToken: authToken,
      profile: profile,
      errorCodes: errorCodes
    )
  }
  func toList() -> [Any?] {
    return [
      reachFiveKey,
      authToken,
      profile,
      errorCodes,
    ]
  }
  static func == (lhs: UpdateProfileRequestInterface, rhs: UpdateProfileRequestInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.reachFiveKey, rhs.reachFiveKey) && deepEqualsreach_five_api(lhs.authToken, rhs.authToken) && deepEqualsreach_five_api(lhs.profile, rhs.profile) && deepEqualsreach_five_api(lhs.errorCodes, rhs.errorCodes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UpdateProfileRequestInterface")
    deepHashreach_five_api(value: reachFiveKey, hasher: &hasher)
    deepHashreach_five_api(value: authToken, hasher: &hasher)
    deepHashreach_five_api(value: profile, hasher: &hasher)
    deepHashreach_five_api(value: errorCodes, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RequestPasswordResetRequestInterface: Hashable {
  var reachFiveKey: ReachFiveKeyInterface
  var email: String? = nil
  var phoneNumber: String? = nil
  var redirectUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RequestPasswordResetRequestInterface? {
    let reachFiveKey = pigeonVar_list[0] as! ReachFiveKeyInterface
    let email: String? = nilOrValue(pigeonVar_list[1])
    let phoneNumber: String? = nilOrValue(pigeonVar_list[2])
    let redirectUrl: String? = nilOrValue(pigeonVar_list[3])

    return RequestPasswordResetRequestInterface(
      reachFiveKey: reachFiveKey,
      email: email,
      phoneNumber: phoneNumber,
      redirectUrl: redirectUrl
    )
  }
  func toList() -> [Any?] {
    return [
      reachFiveKey,
      email,
      phoneNumber,
      redirectUrl,
    ]
  }
  static func == (lhs: RequestPasswordResetRequestInterface, rhs: RequestPasswordResetRequestInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.reachFiveKey, rhs.reachFiveKey) && deepEqualsreach_five_api(lhs.email, rhs.email) && deepEqualsreach_five_api(lhs.phoneNumber, rhs.phoneNumber) && deepEqualsreach_five_api(lhs.redirectUrl, rhs.redirectUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RequestPasswordResetRequestInterface")
    deepHashreach_five_api(value: reachFiveKey, hasher: &hasher)
    deepHashreach_five_api(value: email, hasher: &hasher)
    deepHashreach_five_api(value: phoneNumber, hasher: &hasher)
    deepHashreach_five_api(value: redirectUrl, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UpdatePasswordWithAccessTokenRequestInterface: Hashable {
  var reachFiveKey: ReachFiveKeyInterface
  var authToken: AuthTokenInterface
  var oldPassword: String
  var password: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UpdatePasswordWithAccessTokenRequestInterface? {
    let reachFiveKey = pigeonVar_list[0] as! ReachFiveKeyInterface
    let authToken = pigeonVar_list[1] as! AuthTokenInterface
    let oldPassword = pigeonVar_list[2] as! String
    let password = pigeonVar_list[3] as! String

    return UpdatePasswordWithAccessTokenRequestInterface(
      reachFiveKey: reachFiveKey,
      authToken: authToken,
      oldPassword: oldPassword,
      password: password
    )
  }
  func toList() -> [Any?] {
    return [
      reachFiveKey,
      authToken,
      oldPassword,
      password,
    ]
  }
  static func == (lhs: UpdatePasswordWithAccessTokenRequestInterface, rhs: UpdatePasswordWithAccessTokenRequestInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.reachFiveKey, rhs.reachFiveKey) && deepEqualsreach_five_api(lhs.authToken, rhs.authToken) && deepEqualsreach_five_api(lhs.oldPassword, rhs.oldPassword) && deepEqualsreach_five_api(lhs.password, rhs.password)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UpdatePasswordWithAccessTokenRequestInterface")
    deepHashreach_five_api(value: reachFiveKey, hasher: &hasher)
    deepHashreach_five_api(value: authToken, hasher: &hasher)
    deepHashreach_five_api(value: oldPassword, hasher: &hasher)
    deepHashreach_five_api(value: password, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UpdatePasswordWithFreshAccessTokenRequestInterface: Hashable {
  var reachFiveKey: ReachFiveKeyInterface
  var freshAuthToken: AuthTokenInterface
  var password: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UpdatePasswordWithFreshAccessTokenRequestInterface? {
    let reachFiveKey = pigeonVar_list[0] as! ReachFiveKeyInterface
    let freshAuthToken = pigeonVar_list[1] as! AuthTokenInterface
    let password = pigeonVar_list[2] as! String

    return UpdatePasswordWithFreshAccessTokenRequestInterface(
      reachFiveKey: reachFiveKey,
      freshAuthToken: freshAuthToken,
      password: password
    )
  }
  func toList() -> [Any?] {
    return [
      reachFiveKey,
      freshAuthToken,
      password,
    ]
  }
  static func == (lhs: UpdatePasswordWithFreshAccessTokenRequestInterface, rhs: UpdatePasswordWithFreshAccessTokenRequestInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.reachFiveKey, rhs.reachFiveKey) && deepEqualsreach_five_api(lhs.freshAuthToken, rhs.freshAuthToken) && deepEqualsreach_five_api(lhs.password, rhs.password)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UpdatePasswordWithFreshAccessTokenRequestInterface")
    deepHashreach_five_api(value: reachFiveKey, hasher: &hasher)
    deepHashreach_five_api(value: freshAuthToken, hasher: &hasher)
    deepHashreach_five_api(value: password, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UpdatePasswordWithEmailRequestInterface: Hashable {
  var reachFiveKey: ReachFiveKeyInterface
  var email: String
  var verificationCode: String
  var password: String
  var errorCodes: ErrorCodesInterface


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UpdatePasswordWithEmailRequestInterface? {
    let reachFiveKey = pigeonVar_list[0] as! ReachFiveKeyInterface
    let email = pigeonVar_list[1] as! String
    let verificationCode = pigeonVar_list[2] as! String
    let password = pigeonVar_list[3] as! String
    let errorCodes = pigeonVar_list[4] as! ErrorCodesInterface

    return UpdatePasswordWithEmailRequestInterface(
      reachFiveKey: reachFiveKey,
      email: email,
      verificationCode: verificationCode,
      password: password,
      errorCodes: errorCodes
    )
  }
  func toList() -> [Any?] {
    return [
      reachFiveKey,
      email,
      verificationCode,
      password,
      errorCodes,
    ]
  }
  static func == (lhs: UpdatePasswordWithEmailRequestInterface, rhs: UpdatePasswordWithEmailRequestInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.reachFiveKey, rhs.reachFiveKey) && deepEqualsreach_five_api(lhs.email, rhs.email) && deepEqualsreach_five_api(lhs.verificationCode, rhs.verificationCode) && deepEqualsreach_five_api(lhs.password, rhs.password) && deepEqualsreach_five_api(lhs.errorCodes, rhs.errorCodes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UpdatePasswordWithEmailRequestInterface")
    deepHashreach_five_api(value: reachFiveKey, hasher: &hasher)
    deepHashreach_five_api(value: email, hasher: &hasher)
    deepHashreach_five_api(value: verificationCode, hasher: &hasher)
    deepHashreach_five_api(value: password, hasher: &hasher)
    deepHashreach_five_api(value: errorCodes, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UpdatePasswordWithPhoneNumberRequestInterface: Hashable {
  var reachFiveKey: ReachFiveKeyInterface
  var phoneNumber: String
  var verificationCode: String
  var password: String
  var errorCodes: ErrorCodesInterface


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UpdatePasswordWithPhoneNumberRequestInterface? {
    let reachFiveKey = pigeonVar_list[0] as! ReachFiveKeyInterface
    let phoneNumber = pigeonVar_list[1] as! String
    let verificationCode = pigeonVar_list[2] as! String
    let password = pigeonVar_list[3] as! String
    let errorCodes = pigeonVar_list[4] as! ErrorCodesInterface

    return UpdatePasswordWithPhoneNumberRequestInterface(
      reachFiveKey: reachFiveKey,
      phoneNumber: phoneNumber,
      verificationCode: verificationCode,
      password: password,
      errorCodes: errorCodes
    )
  }
  func toList() -> [Any?] {
    return [
      reachFiveKey,
      phoneNumber,
      verificationCode,
      password,
      errorCodes,
    ]
  }
  static func == (lhs: UpdatePasswordWithPhoneNumberRequestInterface, rhs: UpdatePasswordWithPhoneNumberRequestInterface) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsreach_five_api(lhs.reachFiveKey, rhs.reachFiveKey) && deepEqualsreach_five_api(lhs.phoneNumber, rhs.phoneNumber) && deepEqualsreach_five_api(lhs.verificationCode, rhs.verificationCode) && deepEqualsreach_five_api(lhs.password, rhs.password) && deepEqualsreach_five_api(lhs.errorCodes, rhs.errorCodes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UpdatePasswordWithPhoneNumberRequestInterface")
    deepHashreach_five_api(value: reachFiveKey, hasher: &hasher)
    deepHashreach_five_api(value: phoneNumber, hasher: &hasher)
    deepHashreach_five_api(value: verificationCode, hasher: &hasher)
    deepHashreach_five_api(value: password, hasher: &hasher)
    deepHashreach_five_api(value: errorCodes, hasher: &hasher)
  }
}

private class ReachFiveApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ProviderCreatorTypeInterface(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ProfileAddressTypeInterface(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return ErrorCodesInterface.fromList(self.readValue() as! [Any?])
    case 132:
      return SdkConfigInterface.fromList(self.readValue() as! [Any?])
    case 133:
      return ProviderCreatorInterface.fromList(self.readValue() as! [Any?])
    case 134:
      return ReachFiveKeyInterface.fromList(self.readValue() as! [Any?])
    case 135:
      return ReachFiveConfigInterface.fromList(self.readValue() as! [Any?])
    case 136:
      return ProfileAddressInterface.fromList(self.readValue() as! [Any?])
    case 137:
      return ConsentInterface.fromList(self.readValue() as! [Any?])
    case 138:
      return ProfileSignupRequestInterface.fromList(self.readValue() as! [Any?])
    case 139:
      return SignupRequestInterface.fromList(self.readValue() as! [Any?])
    case 140:
      return AddressInterface.fromList(self.readValue() as! [Any?])
    case 141:
      return OpenIdUserInterface.fromList(self.readValue() as! [Any?])
    case 142:
      return AuthTokenInterface.fromList(self.readValue() as! [Any?])
    case 143:
      return LoginWithPasswordRequestInterface.fromList(self.readValue() as! [Any?])
    case 144:
      return LoginWithProviderRequestInterface.fromList(self.readValue() as! [Any?])
    case 145:
      return RefreshAccessTokenRequestInterface.fromList(self.readValue() as! [Any?])
    case 146:
      return LoginSummaryInterface.fromList(self.readValue() as! [Any?])
    case 147:
      return EmailsInterface.fromList(self.readValue() as! [Any?])
    case 148:
      return ProfileInterface.fromList(self.readValue() as! [Any?])
    case 149:
      return GetProfileRequestInterface.fromList(self.readValue() as! [Any?])
    case 150:
      return UpdateProfileRequestInterface.fromList(self.readValue() as! [Any?])
    case 151:
      return RequestPasswordResetRequestInterface.fromList(self.readValue() as! [Any?])
    case 152:
      return UpdatePasswordWithAccessTokenRequestInterface.fromList(self.readValue() as! [Any?])
    case 153:
      return UpdatePasswordWithFreshAccessTokenRequestInterface.fromList(self.readValue() as! [Any?])
    case 154:
      return UpdatePasswordWithEmailRequestInterface.fromList(self.readValue() as! [Any?])
    case 155:
      return UpdatePasswordWithPhoneNumberRequestInterface.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ReachFiveApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ProviderCreatorTypeInterface {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ProfileAddressTypeInterface {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ErrorCodesInterface {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? SdkConfigInterface {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ProviderCreatorInterface {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ReachFiveKeyInterface {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? ReachFiveConfigInterface {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? ProfileAddressInterface {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? ConsentInterface {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? ProfileSignupRequestInterface {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? SignupRequestInterface {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? AddressInterface {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? OpenIdUserInterface {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? AuthTokenInterface {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? LoginWithPasswordRequestInterface {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? LoginWithProviderRequestInterface {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? RefreshAccessTokenRequestInterface {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? LoginSummaryInterface {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? EmailsInterface {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? ProfileInterface {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? GetProfileRequestInterface {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? UpdateProfileRequestInterface {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? RequestPasswordResetRequestInterface {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? UpdatePasswordWithAccessTokenRequestInterface {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? UpdatePasswordWithFreshAccessTokenRequestInterface {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? UpdatePasswordWithEmailRequestInterface {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? UpdatePasswordWithPhoneNumberRequestInterface {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ReachFiveApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ReachFiveApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ReachFiveApiPigeonCodecWriter(data: data)
  }
}

class ReachFiveApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ReachFiveApiPigeonCodec(readerWriter: ReachFiveApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ReachFiveHostApi {
  func initialize(reachFiveKey: ReachFiveKeyInterface, completion: @escaping (Result<ReachFiveConfigInterface, Error>) -> Void)
  func signup(request: SignupRequestInterface, completion: @escaping (Result<AuthTokenInterface, Error>) -> Void)
  func loginWithPassword(request: LoginWithPasswordRequestInterface, completion: @escaping (Result<AuthTokenInterface, Error>) -> Void)
  func loginWithProvider(request: LoginWithProviderRequestInterface, completion: @escaping (Result<AuthTokenInterface, Error>) -> Void)
  func logout(reachFiveKey: ReachFiveKeyInterface, completion: @escaping (Result<Void, Error>) -> Void)
  func getProfile(request: GetProfileRequestInterface, completion: @escaping (Result<ProfileInterface, Error>) -> Void)
  func updateProfile(request: UpdateProfileRequestInterface, completion: @escaping (Result<ProfileInterface, Error>) -> Void)
  func refreshAccessToken(request: RefreshAccessTokenRequestInterface, completion: @escaping (Result<AuthTokenInterface, Error>) -> Void)
  func requestPasswordReset(request: RequestPasswordResetRequestInterface, completion: @escaping (Result<Void, Error>) -> Void)
  func updatePasswordWithAccessToken(request: UpdatePasswordWithAccessTokenRequestInterface, completion: @escaping (Result<Void, Error>) -> Void)
  func updatePasswordWithFreshAccessToken(request: UpdatePasswordWithFreshAccessTokenRequestInterface, completion: @escaping (Result<Void, Error>) -> Void)
  func updatePasswordWithEmail(request: UpdatePasswordWithEmailRequestInterface, completion: @escaping (Result<Void, Error>) -> Void)
  func updatePasswordWithPhoneNumber(request: UpdatePasswordWithPhoneNumberRequestInterface, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ReachFiveHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ReachFiveApiPigeonCodec.shared }
  /// Sets up an instance of `ReachFiveHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ReachFiveHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reachFiveKeyArg = args[0] as! ReachFiveKeyInterface
        api.initialize(reachFiveKey: reachFiveKeyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let signupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.signup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SignupRequestInterface
        api.signup(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      signupChannel.setMessageHandler(nil)
    }
    let loginWithPasswordChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.loginWithPassword\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loginWithPasswordChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! LoginWithPasswordRequestInterface
        api.loginWithPassword(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loginWithPasswordChannel.setMessageHandler(nil)
    }
    let loginWithProviderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.loginWithProvider\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loginWithProviderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! LoginWithProviderRequestInterface
        api.loginWithProvider(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loginWithProviderChannel.setMessageHandler(nil)
    }
    let logoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.logout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      logoutChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reachFiveKeyArg = args[0] as! ReachFiveKeyInterface
        api.logout(reachFiveKey: reachFiveKeyArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      logoutChannel.setMessageHandler(nil)
    }
    let getProfileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.getProfile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getProfileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! GetProfileRequestInterface
        api.getProfile(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getProfileChannel.setMessageHandler(nil)
    }
    let updateProfileChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.updateProfile\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateProfileChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! UpdateProfileRequestInterface
        api.updateProfile(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateProfileChannel.setMessageHandler(nil)
    }
    let refreshAccessTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.refreshAccessToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      refreshAccessTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RefreshAccessTokenRequestInterface
        api.refreshAccessToken(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      refreshAccessTokenChannel.setMessageHandler(nil)
    }
    let requestPasswordResetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.requestPasswordReset\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPasswordResetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RequestPasswordResetRequestInterface
        api.requestPasswordReset(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPasswordResetChannel.setMessageHandler(nil)
    }
    let updatePasswordWithAccessTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.updatePasswordWithAccessToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePasswordWithAccessTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! UpdatePasswordWithAccessTokenRequestInterface
        api.updatePasswordWithAccessToken(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updatePasswordWithAccessTokenChannel.setMessageHandler(nil)
    }
    let updatePasswordWithFreshAccessTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.updatePasswordWithFreshAccessToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePasswordWithFreshAccessTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! UpdatePasswordWithFreshAccessTokenRequestInterface
        api.updatePasswordWithFreshAccessToken(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updatePasswordWithFreshAccessTokenChannel.setMessageHandler(nil)
    }
    let updatePasswordWithEmailChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.updatePasswordWithEmail\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePasswordWithEmailChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! UpdatePasswordWithEmailRequestInterface
        api.updatePasswordWithEmail(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updatePasswordWithEmailChannel.setMessageHandler(nil)
    }
    let updatePasswordWithPhoneNumberChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_reach_five_platform_interface.ReachFiveHostApi.updatePasswordWithPhoneNumber\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePasswordWithPhoneNumberChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! UpdatePasswordWithPhoneNumberRequestInterface
        api.updatePasswordWithPhoneNumber(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updatePasswordWithPhoneNumberChannel.setMessageHandler(nil)
    }
  }
}
