name: flutter_reach_five_ios
description: iOS implementation of the flutter_reach_five plugin
version: 0.4.2
homepage: https://github.com/bamlab/Flutter-ReachFive

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

flutter:
  plugin:
    implements: flutter_reach_five
    platforms:
      ios:
        pluginClass: FlutterReachFivePlugin
        dartPluginClass: FlutterReachFiveIOS

dependencies:
  flutter:
    sdk: flutter
  flutter_reach_five_platform_interface: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
