name: flutter_reach_five
description: This package allows you to use the methods from the reachFive android and ios native sdks in Flutter
version: 0.4.1
homepage: https://github.com/bamlab/Flutter-ReachFive
repository: https://github.com/bamlab/Flutter-ReachFive

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.16.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_reach_five_android
      ios:
        default_package: flutter_reach_five_ios

dependencies:
  built_value: ^8.9.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_reach_five_android: ^0.4.1
  flutter_reach_five_ios: ^0.4.1
  flutter_reach_five_platform_interface: ^0.4.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  reach_five_identity_repo: ^0.4.1

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.2.12
  equatable_lint: ^0.2.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
