name: flutter_reach_five
description: Flutter Reach Five
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_reach_five_android
      ios:
        default_package: flutter_reach_five_ios

dependencies:
  built_value: ^8.4.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_reach_five_android:
    path: ../flutter_reach_five_android
  flutter_reach_five_ios:
    path: ../flutter_reach_five_ios
  flutter_reach_five_platform_interface:
    path: ../flutter_reach_five_platform_interface
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  reach_five_repo:
    path: ../reach_five_repo

dev_dependencies:
  analyzer: ^4.7.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1
