name: flutter_reach_five
description: This package allows you to use the methods from the reachFive android and ios native sdks in Flutter
version: 0.1.4
homepage: https://github.com/bamlab/Flutter-ReachFive
repository: https://github.com/bamlab/Flutter-ReachFive

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_reach_five_android
      ios:
        default_package: flutter_reach_five_ios

dependencies:
  built_value: ^8.4.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_reach_five_android: ^0.1.4
  flutter_reach_five_ios: ^0.1.4
  flutter_reach_five_platform_interface: ^0.1.4
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  reach_five_identity_repo: ^0.1.4

dev_dependencies:
  analyzer: ^4.7.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1
