name: reach_five_identity_repo
version: 0.1.0
description: OpenAPI API client
homepage: https://github.com/bamlab/Flutter-ReachFive

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dio: '>=4.0.1 <5.0.0'
  json_annotation: '^4.4.0'

dev_dependencies:
  build_runner: any
  json_serializable: '^6.1.5'
  test: ^1.16.0
