name: Test Flutter Reach Five

on:
  push:
    paths:
      - "flutter_reach_five/**"
      - ".github/workflows/flutter_reach_five.yaml"
    branches:
      - main
  pull_request:
    paths:
      - "flutter_reach_five/**"
      - ".github/workflows/flutter_reach_five.yaml"
    branches:
      - main

jobs:
  test:
    strategy:
      matrix: {dir: ["flutter_reach_five"]}
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - uses: actions/checkout@v3.3.0
        
      - id: dotenv
        uses: falti/dotenv-action@v1.0.2
        with:
          path: .github/workflows/.env

      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ steps.dotenv.outputs.flutter_version }}
          channel: "stable"
          cache: true
          cache-key: ${{ runner.os }}-flutter-${{ steps.dotenv.outputs.flutter_version }}
          cache-path: ${{ runner.tool_cache }}/flutter-${{ steps.dotenv.outputs.flutter_version }}

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: dart format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      # Disabled because of this custom lint issue
      # https://github.com/invertase/dart_custom_lint/issues/111
      # - name: Custom lint
      #   run: flutter pub run custom_lint

      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

      - name: Install Remove From Coverage
        run: dart pub global activate remove_from_coverage

      - name: Remove from coverage generated files
        run: remove_from_coverage -f coverage/lcov.info -r '\.gql\.dart$|\.g\.dart$|\.freezed\.dart$'

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          path: "./${{ matrix.dir }}/coverage/lcov.info"
          min_coverage: 100
